/** IKEA desks / conference / foldable (India EN). t: 'desk' | 'table' */
export const ikeaTableDeskRows = [
  {
    c: 'IKEA / Tables',
    n: 'ALEX desk, dark grey, 132x58 cm',
    b: 'IKEA',
    co: 'Dark grey',
    w: null,
    le: '132',
    wi: '58',
    hi: null,
    nw: null,
    d: 'ALEX desk combines smart storage with sleek design. Built-in drawers, generous worktop, and cable management. Minimalist style fits any corner or stands freely in the room.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 16990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/alex-desk-dark-grey__1411362_pe973101_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/alex-desk-dark-grey__1419361_pe976931_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/alex-desk-dark-grey__1470772_pe996946_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/alex-desk-dark-grey-60588889/',
  },
  {
    c: 'IKEA / Tables',
    n: 'LAGKAPTEN / MITTBACK desk, white/birch, 140x60 cm',
    b: 'IKEA',
    co: 'White / birch wood',
    w: null,
    le: '140',
    wi: '60',
    hi: null,
    nw: null,
    d: 'Mix and match table top and legs — ready-made combination. Strong and lightweight construction using less raw material.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 9990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/lagkapten-mittback-desk-white-birch__0976099_pe813002_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-mittback-desk-white-birch__1013982_pe829484_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-mittback-desk-white-birch__1426094_pe979682_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/lagkapten-mittback-desk-white-birch-s99417194/',
  },
  {
    c: 'IKEA / Tables',
    n: 'MITTZON desk, black stained ash veneer/black, 140x60 cm',
    b: 'IKEA',
    co: 'Black / stained ash veneer',
    w: 120,
    le: '140',
    wi: '60',
    hi: null,
    nw: null,
    d: 'Tactile design, adjustable height during assembly. MITTZON desk elevates well-being and focus. 10-year guarantee. Suitable for business use.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 18990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/mittzon-desk-black-stained-ash-veneer-black__1206036_pe907356_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-desk-black-stained-ash-veneer-black__1274110_pe930188_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-desk-black-stained-ash-veneer-black__1273304_pe929983_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/mittzon-desk-black-stained-ash-veneer-black-s99528045/',
  },
  {
    c: 'IKEA / Tables',
    n: 'MALM desk, white, 140x65 cm',
    b: 'IKEA',
    co: 'White',
    w: null,
    le: '140',
    wi: '65',
    hi: null,
    nw: null,
    d: 'Cable shelf under the top keeps cords tidy; back is finished for room-center placement.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 18990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/malm-desk-white__0735975_pe740309_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/malm-desk-white__0662306_pe711832_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/malm-desk-white__1473210_pe997702_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/malm-desk-white-50361754/',
  },
  {
    c: 'IKEA / Tables',
    n: 'LAGKAPTEN / ALEX desk, black-brown, 140x60 cm',
    b: 'IKEA',
    co: 'Black-brown',
    w: null,
    le: '140',
    wi: '60',
    hi: null,
    nw: null,
    d: 'Compact footprint with two drawer units for papers and storage.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 19990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown__1022394_pe832705_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown__1045546_pe842654_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown__1426366_pe979764_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/lagkapten-alex-desk-black-brown-s59432196/',
  },
  {
    c: 'IKEA / Tables',
    n: 'MICKE desk, black-brown, 105x50 cm',
    b: 'IKEA',
    co: 'Black-brown',
    w: null,
    le: '105',
    wi: '50',
    hi: null,
    nw: null,
    d: 'Clean simple look; combine with other MICKE units. Cable tidy at back.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 10990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/micke-desk-black-brown__0735981_pe740299_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/micke-desk-black-brown__0798268_ph165484_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/micke-desk-black-brown__1486116_pe1002309_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/micke-desk-black-brown-00354275/',
  },
  {
    c: 'IKEA / Tables',
    n: 'MICKE desk, white, 105x50 cm',
    b: 'IKEA',
    co: 'White',
    w: null,
    le: '105',
    wi: '50',
    hi: null,
    nw: null,
    d: 'Clean simple look; combine with other MICKE units. Cable tidy at back.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 10990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/micke-desk-white__0736018_pe740345_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/micke-desk-white__0746525_ph151482_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/micke-desk-white__1486116_pe1002309_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/micke-desk-white-80354276/',
  },
  {
    c: 'IKEA / Tables',
    n: 'MITTZON foldable table with castors, white, 140x70 cm',
    b: 'IKEA',
    co: 'White',
    w: null,
    le: '140',
    wi: '70',
    hi: null,
    nw: null,
    d: 'Roll out for meetings; fold and store. Suitable for business use.',
    g: 'Foldable table',
    m: 'Engineered Wood',
    p: 23990,
    t: 'table',
    iu: 'https://www.ikea.com/in/en/images/products/mittzon-foldable-table-with-castors-white__1216218_pe912360_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-foldable-table-with-castors-white__1294133_pe935310_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-foldable-table-with-castors-white__1236719_pe917717_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/mittzon-foldable-table-with-castors-white-90527955/',
  },
  {
    c: 'IKEA / Tables',
    n: 'LAGKAPTEN / ALEX desk, black-brown/white, 120x60 cm',
    b: 'IKEA',
    co: 'Black-brown / white',
    w: null,
    le: '120',
    wi: '60',
    hi: null,
    nw: null,
    d: 'Generous surface and storage for binders and pads. Simple timeless design.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 11490,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown-white__1213334_pe911084_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown-white__1216523_pe912430_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown-white__1215822_pe912213_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/lagkapten-alex-desk-black-brown-white-s59510938/',
  },
  {
    c: 'IKEA / Tables',
    n: 'LAGKAPTEN / ALEX desk, black-brown/white, 140x60 cm',
    b: 'IKEA',
    co: 'Black-brown / white',
    w: null,
    le: '140',
    wi: '60',
    hi: null,
    nw: null,
    d: 'Compact footprint with two drawer units for papers and storage.',
    g: 'Desk',
    m: 'Engineered Wood',
    p: 19990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown-white__1022395_pe832706_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown-white__1045546_pe842654_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/lagkapten-alex-desk-black-brown-white__1160033_pe888711_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/lagkapten-alex-desk-black-brown-white-s89432190/',
  },
  {
    c: 'IKEA / Tables',
    n: 'MITTZON conference table, black stained ash veneer/white, 120x108x105 cm',
    b: 'IKEA',
    co: 'Black stained ash / white',
    w: null,
    le: '120',
    wi: '108',
    hi: '105',
    nw: null,
    d: 'High table for sitting or standing with footrest. Cable management. Suitable for meetings.',
    g: 'Conference table',
    m: 'Engineered Wood',
    p: 21990,
    t: 'table',
    iu: 'https://www.ikea.com/in/en/images/products/mittzon-conference-table-black-stained-ash-veneer-white__1215543_pe912050_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-conference-table-black-stained-ash-veneer-white__1244066_pe921092_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-conference-table-black-stained-ash-veneer-white__1296203_pe935719_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/mittzon-conference-table-black-stained-ash-veneer-white-s89532811/',
  },
  {
    c: 'IKEA / Tables',
    n: 'MITTZON desk sit/stand, electric black stained ash veneer/black, 140x60 cm',
    b: 'IKEA',
    co: 'Black / stained ash veneer',
    w: null,
    le: '140',
    wi: '60',
    hi: null,
    nw: null,
    d: 'Electric sit/stand desk with dual motors. Quality tested for daily use.',
    g: 'Sit/stand desk',
    m: 'Engineered Wood',
    p: 38990,
    t: 'desk',
    iu: 'https://www.ikea.com/in/en/images/products/mittzon-desk-sit-stand-electric-black-stained-ash-veneer-black__1205555_pe907133_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-desk-sit-stand-electric-black-stained-ash-veneer-black__1213137_pe910945_s5.jpg?f=xl | https://www.ikea.com/in/en/images/products/mittzon-desk-sit-stand-electric-black-stained-ash-veneer-black__1274604_pe930418_s5.jpg?f=xl',
    pu: 'https://www.ikea.com/in/en/p/mittzon-desk-sit-stand-electric-black-stained-ash-veneer-black-s29528261/',
  },
]
