/** Urban Ladder coffee tables, study tables, side/C tables. t: 'table' | 'desk' */
export const urbanTableDeskRows = [
  {
    c: 'Collection / Coffee Table',
    n: 'Kaya Solid Wood Coffee Table In Danish Walnut Finish',
    b: 'Urban Ladder',
    co: 'Danish Walnut',
    w: 36,
    le: '60',
    wi: '35',
    hi: '35',
    nw: '24.00 kg',
    d: 'Buy Kaya Organic Solid Wood Coffee Table in Danish Walnut finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 15999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ePHBIgPPk4-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/PzukCsOMzA-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ePHBIgPPk4-a.jpg',
    pu: 'https://www.urbanladder.com/product/kaya-organic-solid-wood-coffee-table-in-danish-walnut-finish-8115700',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Tetra Square Solid Wood Coffee Table With Seats In Danish Walnut Finish In Multicolour Fabric',
    b: 'Urban Ladder',
    co: 'Multicolour fabric',
    w: 36,
    le: '89',
    wi: '89',
    hi: '46',
    nw: '31.80 kg',
    d: 'High solid wood top with four nested ottomans. Plush velvet upholstery, turned solid wood legs, Mango wood frame. Indoor use only.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 27999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/QfO0pLdWEG-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LgL7h8ISiT-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/QfO0pLdWEG-a.jpg',
    pu: 'https://www.urbanladder.com/product/tetra-square-solid-wood-coffee-table-with-seats-in-danish-walnut-finish-in-multicolour-8424835',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Quinn Rectangular Solid Wood Coffee Table In Danish Walnut Finish',
    b: 'Urban Ladder',
    co: 'Danish Walnut',
    w: 36,
    le: '59',
    wi: '42',
    hi: '42',
    nw: '23.40 kg',
    d: 'Curved edges and sculpted frame in solid Mango wood with Danish walnut finish. Indoor use only.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 13999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/C-xwjLzCA4-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fyUuzlqXJT-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/C-xwjLzCA4-a.jpg',
    pu: 'https://www.urbanladder.com/product/quinn-rectangular-solid-wood-coffee-table-in-danish-walnut-finish-8340209',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Linnea Rectangular Solid Wood Coffee Table In Amber Walnut Finish',
    b: 'Urban Ladder',
    co: 'Amber Walnut',
    w: 36,
    le: '55',
    wi: '35',
    hi: '39',
    nw: '19.00 kg',
    d: 'Solid wood coffee table in amber walnut finish. Indoor use only.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 14999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/EIqBx1k1a-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/EIqBx1k1a-a.jpg',
    pu: 'https://www.urbanladder.com/product/linnea-rectangular-solid-wood-coffee-table-in-amber-walnut-finish-9253654',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Tora Solid Wood And Cane With Glass Coffee Table In Amber Walnut Finish',
    b: 'Urban Ladder',
    co: 'Amber Walnut',
    w: 12,
    le: '48',
    wi: '48',
    hi: '46',
    nw: '26.00 kg',
    d: 'Glass top with solid wood and cane base in amber walnut finish. Indoor use only.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 15999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/s6-yra-urY-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/s6-yra-urY-a.jpg',
    pu: 'https://www.urbanladder.com/product/tora-solid-wood-and-cane-with-glass-coffee-table-in-amber-walnut-finish-9253651',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Darren Coffee Table in Columbian Walnut Finish - Gudsmith',
    b: 'Duroflex',
    co: 'Columbian Walnut',
    w: 48,
    le: '60',
    wi: '35',
    hi: '35',
    nw: '13.00 kg',
    d: "Rich aroma of coffee paired with your cozy corner — engineered wood coffee table in Columbian walnut finish.",
    g: 'Coffee table',
    m: 'Engineered Wood',
    p: 4357,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/E2ZGyhU-n--0.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nXShHDEE0m-1.png',
    pu: 'https://www.urbanladder.com/product/darren-coffee-table-in-columbian-walnut-finish-9667543',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Botwin Rectangular Solid Wood Coffee Table In Teak Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Teak',
    w: 36,
    le: '60',
    wi: '35',
    hi: '40',
    nw: '17.35 kg',
    d: 'Buy Botwin Rectangular Solid Wood Coffee Table in Teak Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 9999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Tdn5SeJW9w-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/kchNB-SzEA-1.jpg',
    pu: 'https://www.urbanladder.com/product/botwin-rectangular-solid-wood-coffee-table-in-teak-finish-7518956',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Enzo Set Of 2 Round Solid Wood Coffee Table In Amber Walnut Finish',
    b: 'Urban Ladder',
    co: 'Amber Walnut / Travertine',
    w: 36,
    le: '90',
    wi: '90',
    hi: '37',
    nw: '2.80 kg',
    d: 'Nested set with Travertine stone tops and cylindrical solid-wood legs in amber walnut. Japandi / Oasis Collection.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 44999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JsrnLdZSkp-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/JsrnLdZSkp-LP.jpg',
    pu: 'https://www.urbanladder.com/product/enzo-set-of-2-rectangular-solid-wood-coffee-table-in-amber-walnut-finish-8729969',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Cayman Round Glasstop Coffee Table with Storage in Danish Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Danish Walnut',
    w: 36,
    le: '37',
    wi: '93',
    hi: '37',
    nw: '13.20 kg',
    d: 'Sleek glass top on solid wood base; Danish Walnut finish; optional lower shelf. Indoor use only.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 13999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/go2NDbG85-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/g1dXRtcN3-03.jpg',
    pu: 'https://www.urbanladder.com/product/cayman-glasstop-coffee-table-finish-danish-walnut-8340210',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Paloma Square Marble Coffee Table in Jupiter Spanish Ceramic Finish',
    b: 'Urban Ladder',
    co: 'Jupiter Spanish Ceramic',
    w: 12,
    le: '100',
    wi: '100',
    hi: '40',
    nw: '64.50 kg',
    d: 'Organic stone-look top, bronze-tinted glass shelf, metal legs in latte champagne powder coat. Indoor use only.',
    g: 'Coffee table',
    m: 'Glass',
    p: 44999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/CmSY_bOxZA-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/CmSY_bOxZA-a.jpg',
    pu: 'https://www.urbanladder.com/product/paloma-square-jupiter-spanish-ceramic-coffee-table-9332715',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Avril Rectangular Solid Wood Coffee Table with Seats In Mango Walnut Finish and in Delft Blue Fabric - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Delft Blue / Lagoon Green / Rococo Red',
    w: 36,
    le: '50',
    wi: '46',
    hi: '46',
    nw: '30.50 kg',
    d: 'Buy Avril Rectangular Solid Wood Coffee Table in Mango Walnut Finish & Delft Blue Colour & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Coffee table',
    m: 'Solid Wood',
    p: 13999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/uZf483Jc2w-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3WHhMkcSjW-1.jpg',
    pu: 'https://www.urbanladder.com/product/avril-rectangular-solid-wood-coffee-table-in-mango-walnut-finish-7518953',
  },
  {
    c: 'Collection / Coffee Table',
    n: 'Sienne Round Solid Wood and Toronto Coffee Table in Bronzed Oak Finish',
    b: 'Urban Ladder',
    co: 'Bronzed Oak / Toronto Marble',
    w: 12,
    le: '90',
    wi: '90',
    hi: '46',
    nw: '61.39 kg',
    d: 'Toronto marble top on solid wood pedestal base in bronzed oak finish.',
    g: 'Coffee table',
    m: 'Stone',
    p: 21999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ixW5GpB6b-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ixW5GpB6b-a.jpg',
    pu: 'https://www.urbanladder.com/product/sienne-round-soildwood-and-toronto-coffee-table-in-bronzed-oak-finish-9357510',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Bond Engineered Wood Study Table in Classic Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Classic Walnut',
    w: 12,
    le: '120',
    wi: '48',
    hi: '75',
    nw: '34.50 kg',
    d: 'Buy Bond Engineered Wood Study Table in Classic Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Study table',
    m: 'Engineered Wood',
    p: 5999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Dk2YwQjI1q-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3PzO0v3q2p-1.jpg',
    pu: 'https://www.urbanladder.com/product/bond-engineered-wood-study-table-in-classic-walnut-finish-7519517',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Graham Engineered Wood Study Table in Classic Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Classic Walnut',
    w: 12,
    le: '135',
    wi: '59',
    hi: '75',
    nw: '47.30 kg',
    d: 'Buy Graham Engineered Wood Study Table in Classic Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Study table',
    m: 'Engineered Wood',
    p: 7999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8CA1mcRjI0n-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fjgH6Ngr3j8-1.jpg',
    pu: 'https://www.urbanladder.com/product/graham-engineered-wood-study-table-in-classic-walnut-finish-7519489',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Sidney Engineered Wood Study Table in Rustic Oak Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Rustic Oak',
    w: 12,
    le: '120',
    wi: '54',
    hi: '76',
    nw: '44.00 kg',
    d: 'Buy Sidney Engineered Wood Study Table in Rustic Oak Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Study table',
    m: 'Engineered Wood',
    p: 19999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/cFfe6j2Ffh-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/80O1WKN3C--1.jpg',
    pu: 'https://www.urbanladder.com/product/sidney-engineered-wood-study-table-in-rustic-oak-finish-7519504',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Truman Study Table Creamy Crust in Danish Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Danish Walnut / Creamy Crust',
    w: 36,
    le: '120',
    wi: '59',
    hi: '76',
    nw: '33.35 kg',
    d: 'Solid wood study table in Danish walnut finish with creamy crust top detail.',
    g: 'Study table',
    m: 'Solid Wood',
    p: 14999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/rAapcPip3-Truman-Study-Table-Creamy-Crust-in-Danish-Walnut-Finish.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/bdmr9TkIn-b.jpg',
    pu: 'https://www.urbanladder.com/product/truman-study-table-creamy-crust-finish-danish-walnut-8425971',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Twain Engineered Wood Study Table in Cherry Melamine Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Cherry Melamine',
    w: 12,
    le: '120',
    wi: '60',
    hi: '74',
    nw: '5.60 kg',
    d: 'Buy Twain Engineered Wood Study Table in Cherry Melamine Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Study table',
    m: 'Engineered Wood',
    p: 10999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/az69TmqxeO-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nluT8K8-yZ-1.jpg',
    pu: 'https://www.urbanladder.com/product/twain-engineered-wood-study-table-in-cherry-melamine-finish-7519505',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Bradbury Desk Size Large In Amber Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Amber Walnut',
    w: 36,
    le: '140',
    wi: '70',
    hi: '74',
    nw: '30.80 kg',
    d: 'Solid wood desk with internal storage, smooth drawers, modular reversible storage. Indoor use only.',
    g: 'Study table',
    m: 'Solid Wood',
    p: 23999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ESOxmh2cVB-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/q-EBMYqIU2-c.jpg',
    pu: 'https://www.urbanladder.com/product/bradbury-desk-size-large-in-amber-walnut-metal-channel-8340148',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Larsson Study Table in Danish Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Danish Walnut',
    w: 36,
    le: '120',
    wi: '59',
    hi: '80',
    nw: '28.85 kg',
    d: 'Solid wood study table with built-in drawer and wire manager. Danish Walnut variant with metal drawer channels. Indoor use only.',
    g: 'Study table',
    m: 'Solid Wood',
    p: 11999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UZPNyFDwf8-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Uw6QqQzaX-b.jpg',
    pu: 'https://www.urbanladder.com/product/larsson-study-table-finish-danish-walnut-metal-channel-8340910',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Angelou Solid Wood Study Table in Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Walnut',
    w: 36,
    le: '140',
    wi: '70',
    hi: '77',
    nw: '33.35 kg',
    d: 'Buy Angelou Solid Wood Study Table in Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Study table',
    m: 'Solid Wood',
    p: 13999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DxTHUhNBvg-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Em8xzhQi2O-1.jpg',
    pu: 'https://www.urbanladder.com/product/angelou-solid-wood-study-table-in-walnut-finish-7519515',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Tylor Engineered Wood Study Table in Classic Walnut Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Classic Walnut',
    w: 12,
    le: '120',
    wi: '60',
    hi: '76',
    nw: '31.90 kg',
    d: 'Two-tone engineered wood desk with wire manager, drawer and open shelf. Indoor use only.',
    g: 'Study table',
    m: 'Engineered Wood',
    p: 5999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/TJqKypkrGx-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/xJEPjQ1c5P-1.jpg',
    pu: 'https://www.urbanladder.com/product/tylor-engineered-wood-study-table-in-classic-walnut-finish-7519512-9420854',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Dickens Solid Wood Study Table in Teak Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Teak',
    w: 36,
    le: '150',
    wi: '85',
    hi: '75',
    nw: '20.75 kg',
    d: 'Buy Dickens Solid Wood Study Table in Teak Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Study table',
    m: 'Solid Wood',
    p: 26999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Y484GBBASN-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fqYzL8ra8t-1.jpg',
    pu: 'https://www.urbanladder.com/product/dickens-solid-wood-study-table-in-teak-finish-7519518',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Austen Compact Desk in Two Tone Finish - Urban Ladder',
    b: 'Urban Ladder',
    co: 'Two tone / Amber Walnut & Mahogany',
    w: 36,
    le: '100',
    wi: '40',
    hi: '73',
    nw: '23.25 kg',
    d: 'Compact solid wood desk in two-tone amber walnut and mahogany.',
    g: 'Study table',
    m: 'Solid Wood',
    p: 10999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/kSO7NMd5aZ-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lLHQ1-83-s-b.jpg',
    pu: 'https://www.urbanladder.com/product/austen-compact-desk-finish-two-tone-amber-walnut-and-mahogany-8425970',
  },
  {
    c: 'Collection / Study Tables',
    n: 'Fidora Study Table Finish - Teak',
    b: 'Urban Ladder',
    co: 'Teak',
    w: 36,
    le: '120',
    wi: '54',
    hi: '76',
    nw: '60.00 kg',
    d: 'Buy Fidora Study Table, Finish - Teak & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Study table',
    m: 'Solid Wood',
    p: 18999,
    t: 'desk',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Puj_b15QOD-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Puj_b15QOD-LP.jpg',
    pu: 'https://www.urbanladder.com/product/fidora-study-table-finish-teak-8115735',
  },
  {
    c: 'Collection / Tables',
    n: 'Takai Solid Wood Side Table In Red Cedar Finish',
    b: 'Urban Ladder',
    co: 'Red Cedar',
    w: 36,
    le: '45',
    wi: '45',
    hi: '50',
    nw: '22.00 kg',
    d: 'Mango wood side table in red cedar finish. Japandi-inspired Takai range.',
    g: 'Side table',
    m: 'Solid Wood',
    p: 11999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/4v6Uhuv3RL-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/4v6Uhuv3RL-a.jpg',
    pu: 'https://www.urbanladder.com/product/takai-solid-wood-side-table-in-red-cedar-finish-8861194',
  },
  {
    c: 'Collection / Tables',
    n: 'Tory Metal Sofa C Table In Gold Finish',
    b: 'Urban Ladder',
    co: 'Gold',
    w: 12,
    le: '47',
    wi: '32',
    hi: '66',
    nw: '8.00 kg',
    d: 'Metal C-side / sofa table in gold finish.',
    g: 'Side table',
    m: 'Metal',
    p: 6999,
    t: 'table',
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/sEU28W1yW-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sEU28W1yW-a.jpg',
    pu: 'https://www.urbanladder.com/product/tory-sofa-c-table-in-gold-finish-9264497',
  },
]
