/** Urban Ladder chair / study chair rows for chair_products seed (compact keys). */
export const urbanLadderChairs = [
  {
    c: 'Collection / Chairs',
    n: 'Florence Lounge Chair in Calico Floral Colour',
    b: 'Urban Ladder',
    co: 'Calico Floral',
    w: 36,
    le: '63',
    wi: '60',
    hi: '74',
    nw: '12.35 kg',
    d: 'Buy Florence Lounge Chair in Calico Floral & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Lounge chair',
    m: 'Solid Wood',
    p: 10999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TtBHiaucODy-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/z90x3lqR8mg-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/toOYb5RJiia-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/4wteQea1e_M-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FaH_dQgzRpn-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/QdEqBiEtW1y-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/cn5eOTApo2R-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Fqr-uhs2T8t-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/TtBHiaucODy-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/7UXJahccjzI-2.jpg',
    pu: 'https://www.urbanladder.com/product/florence-lounge-chair-in-calico-floral-7520492',
  },
  {
    c: 'Collection / Chairs',
    n: 'Genoa Wing Chair in Monochrome Paisley Colour',
    b: 'Urban Ladder',
    co: 'Monochrome Paisley',
    w: 12,
    le: '69',
    wi: '95',
    hi: '1',
    nw: '0.03 kg',
    d: 'Buy Genoa Wing Chair in Monochrome Paisley Colour & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Wing chair',
    m: 'Fabric',
    p: 17999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9LEkLEtg9ia-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gI5h5MH0f-H-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_VIU1GK2Jvz-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5oVsS30R3_r-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/lF0eOOz_FTa-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ZZ9ecS248fU-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/j4wbesBqJs8-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/d3kwVIo3v-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/9LEkLEtg9ia-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/E0AeP8AvY--2.jpg',
    pu: 'https://www.urbanladder.com/product/genoa-wing-chair-in-monochrome-paisley-colour-8148076',
  },
  {
    c: 'Collection / Chairs',
    n: 'Odette Lounge Chair In Army Green Leather',
    b: 'Urban Ladder',
    co: 'Army Green, Brown, Burgundy, Mustard',
    w: 12,
    le: '82',
    wi: '84',
    hi: '74',
    nw: '30.00 kg',
    d: "There's something irresistibly inviting about the Odette lounge chair — soft curves, supple leather, and an easy elegance that calls you to sink right in. Its smooth upholstery lends a touch of luxury, the kind that guests can't help but admire and reach out to feel. Shaped for comfort, its enveloping seat encourages you to unwind, and simply be. The slender legs bring balance to its generous form, while the overarching armrests complete the silhouette with effortless grace. A blend of substance and style, Odette makes relaxation look and feel exceptional. - Available in 4 leather upholstery options: Army Green, Burgundy, Brown and Mustard.",
    g: 'Lounge chair',
    m: 'Leather',
    p: 44999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/a4krcM57CM-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Qy0s8yUPyg-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/WYE97Lb503-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/1QixAguOk5-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fboZvWr8w0-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TCm8Tj9vtA-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/74eeo2s-SE-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/WlcaI7XOyz-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/a4krcM57CM-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Qy0s8yUPyg-2.jpg',
    pu: 'https://www.urbanladder.com/product/odette-lounge-chair-in-army-green-leather-9322473',
  },
  {
    c: 'Collection / Chairs',
    n: 'Morgen Lounge Chair in Calico Print Colour',
    b: 'Urban Ladder',
    co: 'Calico Print',
    w: 12,
    le: '70',
    wi: '88',
    hi: '1',
    nw: '29.50 kg',
    d: 'Buy Morgen Lounge Chair in Calico Print Fabric & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Lounge chair',
    m: 'Solid Wood',
    p: 16999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_GGO3rKfn4X-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FZQl6_m4iTM-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nXHqxrHJwDU-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/hFgGK7gMBJH-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/wTdk__anM6C-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/K05CMWsL5-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/KO7FsxFSCc-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ZZmhVcN45O-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_GGO3rKfn4X-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/DXXYtdNvJC-1.jpg',
    pu: 'https://www.urbanladder.com/product/morgen-lounge-chair-in-calico-print-fabric-7520462',
  },
  {
    c: 'Collection / Chairs',
    n: 'Eclipse Lounge Chair in Pixel Blue Colour',
    b: 'Urban Ladder',
    co: 'Pixel Blue, Abstract Taupe, Charcoal',
    w: 12,
    le: '87',
    wi: '91',
    hi: '74',
    nw: '33.00 kg',
    d: 'The Eclipse lounge chair wraps you in comfort with its cocooning, barrel-shaped form. Its curved back flows seamlessly into the arms, creating an enveloping silhouette that encourages you to unwind. The circular seat rests on a sculpted wooden plinth base, adding warmth and stability while maintaining a sleek, modern edge. Perfect as an accent in your living room or reading corner, it strikes a balance between statement design and everyday ease. - Available in 3 colour options: Abstract Taupe, Pixel Blue, and Charcoal.',
    g: 'Lounge chair',
    m: 'Fabric',
    p: 39999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fAiZ25EVsnq-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YgSje18Gkce-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/kXtxnUYW-vv-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/B9GmgC_AFPZ-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/g_KYuYAVPJn-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5UBZpaPvXqe-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_rY1_L1LIBM-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nRbPP8wT45z-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fAiZ25EVsnq-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/jq33NR7msb6-2.jpg',
    pu: 'https://www.urbanladder.com/product/eclipse-lounge-chair-in-pixel-blue-fabric-9283679',
  },
  {
    c: 'Collection / Chairs',
    n: 'Bella Lounge Chair Finish Teak Beige Flora Colour',
    b: 'Urban Ladder',
    co: 'Beige Flora',
    w: 36,
    le: '56',
    wi: '61',
    hi: '73',
    nw: '9.60 kg',
    d: 'Buy Bella Lounge chair -Finish - Teak, Fabric - IC - F - 18 & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Lounge chair',
    m: 'Solid Wood',
    p: 8499,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7xsEl2c1Xe-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/yEDprYS478-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-v36Sls3OU-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TPb2O6XdWa-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/sCRADtIlIz-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/IqJU_f06kF-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fcfyuY7puB-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/DZm67qiYP8-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/7xsEl2c1Xe-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/j_EpcsBEfCk-2.jpg',
    pu: 'https://www.urbanladder.com/product/bella-lounge-chair-finish-teak-fabric-ic-f-18-8115772',
  },
  {
    c: 'Collection / Chairs',
    n: 'Selene Upholstered Accent Chair In Light Grey Fabric',
    b: 'Urban Ladder',
    co: 'Cedar Green, Light Grey, Mustard',
    w: 12,
    le: '61',
    wi: '59',
    hi: '82',
    nw: '11.50 kg',
    d: 'Designed to impress from every angle, the Selene accent chair combines sculptural beauty with everyday comfort. Its continuous curved back and armrests flow into a plush, contoured seat, creating a soft yet structured form. The conical tapered base offers a grounded, modern aesthetic, while the 360° swivel adds ease and flexibility to your dining or lounge experience. Fully upholstered in premium fabrics and fresh colorways, it brings a sense of effortless sophistication to any space.',
    g: 'Accent chair',
    m: 'Fabric',
    p: 11999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/GoeveV_6iI-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FXY4dzPmXP-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0wWhTxHuPg-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0UjLanv18D-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/D0KAv5TGWN-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/xGkbC7ldic-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0WELdBcSMf-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/vXQefTCXiv-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/GoeveV_6iI-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/fS9p4xQ8FxT-2.jpg',
    pu: 'https://www.urbanladder.com/product/selene-upholstered-accent-chair-in-light-grey-fabric-9253642',
  },
  {
    c: 'Collection / Chairs',
    n: 'Chandigarh Lounge Chair in Rustic Green Damask Colour',
    b: 'Urban Ladder',
    co: 'Rustic Green Damask',
    w: 36,
    le: '76',
    wi: '62',
    hi: '83',
    nw: '15.50 kg',
    d: 'Buy Chandigarh Lounge Chair in Rustic Green Damask fabric & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Lounge chair',
    m: 'Fabric',
    p: 15999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7WYIWdCQZ-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gbeMXCL0sI-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/dDQxJhucJ7-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/cqvzJjlKbr-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/t1uTHJf7YD-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/aLZolqhF3u-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/8s4DXzRnsP-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Mm5AdIT5Ck-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/7WYIWdCQZ-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/mAw8PR5d0x6-2.jpg',
    pu: 'https://www.urbanladder.com/product/chandigarh-lounge-chair-in-rustic-green-damask-fabric-8144313',
  },
  {
    c: 'Collection / Chairs',
    n: 'Reno Lounge Chair in Rust Himalaya Boucle Colour',
    b: 'Urban Ladder',
    co: 'Rust Himalaya Boucle',
    w: 36,
    le: '98',
    wi: '94',
    hi: '72',
    nw: '48.40 kg',
    d: 'Buy Reno Lounge Chair in Rust Himalaya Boucle fabric & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
    g: 'Lounge chair',
    m: 'Solid Wood',
    p: 22999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ABjgmZ8KzT-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/vDmzZzATgV-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/IwYQJdG5NY-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/vcxhthvBlI-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/S948p4NT7C-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/mPwIk8oLga-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/oAmRZcHEV3-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gl6wUEe7LV-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ABjgmZ8KzT-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Ju-0oGM8vf0-2.jpg',
    pu: 'https://www.urbanladder.com/product/reno-lounge-chair-in-rust-himalaya-boucle-fabric-8115770',
  },
  {
    c: 'Collection / Chairs',
    n: 'Juniper Lounge Chair in Deep Crimson Velvet',
    b: 'Urban Ladder',
    co: 'Aztec Brown Velvet, Deep Crimson Velvet, White Sand Boucle',
    w: 12,
    le: '66',
    wi: '75',
    hi: '74',
    nw: '25.00 kg',
    d: 'Artful and expressive, the Juniper lounge chair makes a bold statement through form and texture. Its sculptural silhouette, defined by a continuous curve that flows seamlessly from back to arm, strikes the perfect balance between comfort and character. The open-back cut-out introduces lightness, allowing the design to breathe while adding visual intrigue from every angle.',
    g: 'Lounge chair',
    m: 'Solid Wood',
    p: 17999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FVmaCGX6cg-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Y8u2x9nkiY-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nsqSUPHHm9-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/PgkMqKTONR-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/UqylJy3olI-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/KLBlg7nllY-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MCqluupDu6-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/2B_cscyCdMX-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/FVmaCGX6cg-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/OUi6l_jsA0H-2.jpg',
    pu: 'https://www.urbanladder.com/product/juniper-lounge-chair-in-deep-crimson-velvet-9275530',
  },
  {
    c: 'Collection / Chairs',
    n: 'Arna Lounge Chair In Aztec Bloom Velvet Colour',
    b: 'Urban Ladder',
    co: 'Aztec Bloom',
    w: 12,
    le: '71',
    wi: '66',
    hi: '80',
    nw: '20.00 kg',
    d: 'The Arna lounge chair brings together natural texture and modern ease in perfect harmony. Its solid ash wood frame, detailed with woven cane panels, creates a breathable silhouette that feels both nostalgic and new. Plush velvet cushions invite you to sink in, balancing softness with sculptural form.',
    g: 'Lounge chair',
    m: 'Solid Wood',
    p: 22999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/k9y1tbqoqv-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/HeqsECfIJW-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/t6evUlyXQM-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/GbMakhwUsT-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/tFZ5N3g_dp-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/QBxSjqWGGh-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/D4wef7hGkg-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/UDguO47owQ-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/k9y1tbqoqv-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/HeqsECfIJW-2.jpg',
    pu: 'https://www.urbanladder.com/product/arna-lounge-chair-in-aztec-bloom-velvet-9275525',
  },
  {
    c: 'Collection / Chairs',
    n: 'Dakota Lounge Chair In Stria Beige Colour',
    b: 'Urban Ladder',
    co: 'Stria Beige',
    w: 12,
    le: '82',
    wi: '70',
    hi: '84',
    nw: '30.00 kg',
    d: 'The Dakota lounge chair brings mid-century sophistication into modern living. Its form flows with gentle ease, defined by a softly reclined backrest and a rounded seat that invites you to unwind. The open-frame arms and legs, crafted from solid teak wood, reveal warm natural grains and fluid contours that celebrate craftsmanship in its purest form.',
    g: 'Lounge chair',
    m: 'Solid Wood',
    p: 23999,
    iu: 'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ni67CZ5Vi-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/V9BZ16Edt-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/qoUg_FmJ8J-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/G3LVcd3Vke-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/csem6-xgmo-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/QdSwrRZJ0N-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/P1Dc4xkeyB-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ogo_OrX_HV-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ni67CZ5Vi-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/V9BZ16Edt-2.jpg',
    pu: 'https://www.urbanladder.com/product/dakota-lounge-chair-in-stria-beige-9322472',
  },
];
