-- Additional sofa, recliner, and sofa-cum-bed products for sofa_products table.
-- Run after 009_sofa_products.sql and 009_sofa_products_seed.sql (if used).

INSERT INTO sofa_products (name, brand, colour, warranty_in_months, country_of_origin, length, width, height, net_weight, description, generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name, price, images_url, product_url) VALUES
(
  'Vetra 3 Seater Leather Sofa In Olive Colour',
  'Urban Ladder',
  'Olive',
  12,
  'Vietnam',
  '94.00 cm',
  '2.32 m',
  '88.00 cm',
  '60.00 kg',
  'Vetra balances modern minimalism with plush, inviting comfort. Its streamlined silhouette and angled armrests create an elegant presence, while stitched back cushions add a textured detail that captivates the eye. Upholstered in smooth, premium leather, the sofa develops a natural patina over time that enriches its character. Elevated on dark chrome-finished legs, it brings a sense of lightness while grounding your living room. Perfect for urban and minimalist interiors, the Vetra sofa turns every space into a statement. Available in three colour options: Olive, White and Wine. Available in 1, 2 and 3 seater options. Dark chrome-finished metal legs.',
  NULL,
  'Leather',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  89999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/uCtAB2Irm4-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Qyl4NG3K2g-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/JyiJu7kQz4-c.jpg',
  'https://www.urbanladder.com/product/vetra-3-seater-leather-sofa-in-olive-9227440'
),
(
  'Raynor 3 Seater Wooden Sofa in Midnight Indigo Blue Colour',
  'Urban Ladder',
  'Midnight Indigo Blue',
  NULL,
  'India',
  '1.83 m',
  '78.74 cm',
  '81.28 cm',
  '51.00 kg',
  'Buy Raynor 3 seater wooden sofa, Finish- Amber Walnut, Fabric - Midnight Indigo Blue & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
  NULL,
  'Solid Wood',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  32999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2Vr7wyWwQH-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/s-qPIo73zN-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/FBPrTBUUwK-c.jpg',
  'https://www.urbanladder.com/product/raynor-3-seater-wooden-sofa-finish-amber-walnut-fabric-midnight-indigo-blue-8115799'
),
(
  'Emila Fabric Three Seater Motorized Recliner in Blue Colour',
  'Urban Ladder',
  'Blue',
  12,
  NULL,
  '96.00 cm',
  '2.32 m',
  '99.00 cm',
  '66.25 kg',
  'The Emila Recliner transforms everyday lounging into a luxurious ritual. At the push of a button, its motorised recline function eases you into relaxation, adapting seamlessly to your comfort needs. Thoughtfully designed, the backrest glides into position without demanding extra space, making it a perfect fit for any room. Plush armrests, headrests, and deep-cushioned seats invite you to sink in and unwind. A discreet button console with a built-in USB port keeps your devices charged, while sleek stainless steel legs add a contemporary touch. Available in 1-seater, 2-seater and 3-seater options. Available in Blue, Grey and Cream colour options. Indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  99999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sqpM7TjTMK-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fUQSRCM_sT-2.jpg',
  'https://www.urbanladder.com/product/emila-fabric-three-seater-motorized-recliner-in-blue-colour-7520170-8721015'
),
(
  'Linaro Leather 3 Seater Double Motor Recliner In Blue Colour',
  'Urban Ladder',
  'Blue',
  12,
  NULL,
  '1.07 m',
  '2.12 m',
  '98.00 cm',
  '83.00 kg',
  'The Linaro recliner is designed with a modern, cocooning silhouette that invites you in. Dark-chrome accents trace its form, accentuating its elegant presence. A discreetly placed switch outside the armrest offers intuitive control. With a dual motor mechanism, the backrest and footrest move independently, adapting to your every mood. Upholstered in premium leather, the Linaro recliner brings effortless luxury to your living space. Premium leather upholstery. Available in 2 colour options: Grey and Blue. 1, 2 and 3 seater options. Dark-chrome metal accents.',
  NULL,
  'Leather',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  139999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/c0okulYmF-Linaro-Leather-3-Seater-Double-Motor-Recliner-In-Blue-Colour.jpeg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/BiCdRo0h5Rb-2.jpg',
  'https://www.urbanladder.com/product/linaro-leather-3-seater-double-motor-recliner-in-blue-colour-9264847'
),
(
  'Lebowski Fabric One Seater Manual Recliner in Cobalt Fabric Colour',
  'Urban Ladder',
  'Cobalt Fabric',
  12,
  NULL,
  '81.00 cm',
  '92.50 cm',
  '1.03 m',
  '45.15 kg',
  'Some moments deserve to be savoured. The Lebowski recliner is designed for just that. With its plush upholstery and inviting silhouette, this recliner sofa transforms any corner of your home into a sanctuary of relaxation. The manual reclining mechanism allows you to adjust your position with a simple pull. Crafted for durability, each seat has been rigorously tested to support up to 140 kg. Available in single-seater, two-seater, and three-seater configurations. Choose from leatherette and fabric upholstery. Indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  16999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/o7IZQrlbbu-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/q5Gp5gs77L-2.jpg',
  'https://www.urbanladder.com/product/lebowski-fabric-one-seater-manual-recliner-in-cobalt-fabric-colour-7520195-8720973'
),
(
  'Atticus Single Seater Swivel Rock Recliner in Baltic Blue Colour',
  'Urban Ladder',
  'Baltic Blue',
  12,
  NULL,
  '1.07 m',
  '1.02 m',
  '1.08 m',
  '30.00 kg',
  'Experience premium comfort and versatility with the Atticus Single-Seater Recliner. Wrapped in plush fabric, this contemporary recliner brings both style and advanced functionality to your living space. Its innovative swivel capability gives you the freedom to shift your focus without having to reposition the entire recliner. The gentle rocking motion adds another dimension of relaxation. Available in both motorized and manual reclining mechanisms. Available in three colour options: Urban Grey, Baltic Blue and Shitake Beige. Indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  27999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/OZSupga4Yx-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-bQP8daY5F-2.jpg',
  'https://www.urbanladder.com/product/atticus-single-seater-swivel-rock-recliner-7520202-8721050'
),
(
  'Griffin Fabric One Seater Manual Recliner in Lapis Blue Fabric Colour',
  'Urban Ladder',
  'Lapis Blue Fabric',
  12,
  NULL,
  '93.90 cm',
  '96.50 cm',
  '98.00 cm',
  '50.80 kg',
  'Poised and plush. With a generously cushioned body and a classic shape, Griffin recliner is a seat treat. Covered in premium upholstery, the recliner mechanism allows you to lean almost 180 degrees back and also unfolds with a footprint, giving you maximum comfort. Choose from leatherette or fabric upholstery. Tested for 25,000 cycles. Load-bearing capacity testing for up to 140kg on each seat. Indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  21999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/tzNTKDW4H7v-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/EbkwCO19Uni-2.jpg',
  'https://www.urbanladder.com/product/griffin-fabric-one-seater-manual-recliner-in-lapis-blue-fabric-colour-7520212-8721003'
),
(
  'Raphael Leatherette One Seater Manual Recliner in Off White Colour',
  'Urban Ladder',
  'Off White',
  12,
  NULL,
  '1.02 m',
  '96.60 cm',
  '99.10 cm',
  '27.00 kg',
  'Lounge like you mean it. Snuggle up in the plush cushioning of our Raphael 2 Seater Recliner. A perfect blend of style and functionality, this transitional style 3 position manual recliner comes with a smooth glide mechanism, puffed armrests and a cushioned headrest that will help you relax and stretch in comfort.',
  NULL,
  'Leatherette',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  22999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/o8dIHwwaoH-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/at98ARgUCa-2.jpg',
  'https://www.urbanladder.com/product/raphael-leatherette-one-seater-manual-recliner-in-off-white-colour-7520179-8720998'
),
(
  'Bernice One Seater Recliner in Tan Colour',
  'Urban Ladder',
  'Tan',
  12,
  NULL,
  '93.00 cm',
  '1.01 m',
  '99.00 cm',
  '29.00 kg',
  'Lounge like you mean it. Snuggle up in the plush cushioning of our Bernice 1 Seater Recliner. A perfect blend of style and functionality, this contemporary style 3 position manual recliner comes with a smooth glide mechanism, puffed armrests and a cushioned headrest that will help you relax and stretch in comfort.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  23999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nRORdWju_Zl-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZzxpUfqtEzT-2.jpg',
  'https://www.urbanladder.com/product/bernice-one-seater-recliner-in-tan-colour-7520196-8720986'
),
(
  'Dawson Fabric One Seater Manual Recliner in Coastal Blue Colour',
  'Urban Ladder',
  'Coastal Blue',
  12,
  NULL,
  '83.00 cm',
  '92.00 cm',
  '1.03 m',
  '40.00 kg',
  'Dawson Single Seater Entertainment Recliner – where style meets comfort for your ultimate relaxation experience. This modern recliner is designed with both aesthetics and functionality in mind, making it a perfect addition to your living room, home theater, or entertainment space. Keep your favorite beverages within reach. For indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  18999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XsW1ZxgfU2-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/npCycrJTpA-2.jpg',
  'https://www.urbanladder.com/product/dawson-fabric-one-seater-manual-recliner-in-coastal-blue-colour-7520169-8720972'
),
(
  'Edison Single Seater Recliner in Matte Grey Colour',
  'Urban Ladder',
  'Matte Grey',
  6,
  NULL,
  '90.93 cm',
  '81.03 cm',
  '1.04 m',
  '46.00 kg',
  'Buy Edison Single Seater Recliner in Matte Grey Fabric & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  14999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_PJnGPQ1tW-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/JHvtpLMpTo-2.jpg',
  'https://www.urbanladder.com/product/edison-single-seater-recliner-in-matte-grey-fabric-8144331'
),
(
  'Marvin Entertainment Recliner in Beige Colour',
  'Urban Ladder',
  'Beige',
  24,
  NULL,
  '2.02 m',
  '90.93 cm',
  '95.00 cm',
  '146.00 kg',
  'Buy Marvin Entertainment Recliner in Beige & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  NULL,
  NULL,
  79999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_-omLxkf9-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZlyUH4rE6s-b.jpg',
  'https://www.urbanladder.com/product/marvin-entertainment-recliner-in-beige-8144342'
),
(
  'Mohave Leather Recliner',
  'Urban Ladder',
  NULL,
  12,
  NULL,
  '86.11 cm',
  '56.13 cm',
  '1.02 m',
  '71.20 kg',
  'Leather recliner by Urban Ladder.',
  NULL,
  'Leather',
  NULL,
  NULL,
  NULL,
  NULL,
  69999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/MEh_Y1Aten-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/hSXFJT_MFr-2.jpg',
  'https://www.urbanladder.com/product/mohave-leather-recliner-8294279'
),
(
  'Marlowe Single Seater Motorised Recliner in Ancient Ivory Cream Leatherette Colour',
  'Urban Ladder',
  'Ancient Ivory Cream Leatherette',
  24,
  NULL,
  '89.92 cm',
  '89.92 cm',
  '98.04 cm',
  '44.00 kg',
  'Buy Marlowe Single Seater Motorised Recliner in Ancient Ivory Cream Leatherette & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
  NULL,
  'Leatherette',
  NULL,
  NULL,
  '1 Seater',
  NULL,
  29999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/HtVP_ZEa8JV-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/0R6Ldpecu85-2.jpg',
  'https://www.urbanladder.com/product/marlowe-single-seater-motorised-recliner-in-ancient-ivory-cream-leatherette-8144340'
),
(
  'Camden Compact 3 Seater Pull Out Sofa cum Bed In Salsa Red Colour',
  'Urban Ladder',
  'Salsa Red',
  12,
  NULL,
  '2.00 m',
  '1.50 m',
  '69.00 cm',
  '87.35 kg',
  'A gorgeous three-seater, the Camden compact sofa cum bed works not just as your primary seating option, but also as an elegant statement piece. It transforms easily from sofa to bed, in three simple steps. Easy to pull out, easy to put back. Make an instant guest room whenever you need. Its armrests are steady and reliable.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  34999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/VE84mycKg0P-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/uAia7ojmDQ9-2.png',
  'https://www.urbanladder.com/product/camden-compact-3-seater-pull-out-sofa-cum-bed-in-salsa-red-colour-7518888-8687470'
),
(
  'Felicity 3 Seater Click Clack Sofa cum Bed In Olive Green Colour',
  'Urban Ladder',
  'Olive Green',
  12,
  NULL,
  '81.30 cm',
  '1.99 m',
  '84.50 cm',
  '58.65 kg',
  'Plush and comfy, the Felicity is every insomniac''s dream come true. A gentle push turns it into an inviting single bed. Perfect for small apartments and sudden guests. Made of eucalyptus wood. Foam cushioning. Fabric upholstery. The click-clack mechanism for ease of use.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  24999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/CnkvrmYvDS-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lakeq5ccmQ-1.jpg',
  'https://www.urbanladder.com/product/felicity-3-seater-click-clack-sofa-cum-bed-in-olive-green-colour-7518906-8687510'
),
(
  'Palermo 3 Seater Click Clack Sofa cum Bed In Midnight Indigo Blue Colour',
  'Urban Ladder',
  'Midnight Indigo Blue',
  12,
  NULL,
  '1.23 m',
  '1.87 m',
  '40.80 cm',
  '60.50 kg',
  'Some moments call for conversation, others for quiet relaxation. With the Palermo Sofa-Cum-Bed, you never have to choose. Designed for modern living, this plush three-seater welcomes you with soft fabric and generous cushioning. When the need arises, it transforms into a cosy twin bed with a simple click-clack mechanism. Available in 3 options: Olive Green, Salsa Red and Midnight Indigo Blue. Indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  24999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-kn99h-LC-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-OFidGz23p-2.jpg',
  'https://www.urbanladder.com/product/palermo-3-seater-click-clack-sofa-cum-bed-in-midnight-indigo-blue-colour-7518902-8687574'
),
(
  'Peckham 3 Seater Click Clack Sofa Cum Bed In Ocean Weave Colour',
  'Urban Ladder',
  'Ocean Weave',
  12,
  NULL,
  '1.39 m',
  '2.04 m',
  '78.00 cm',
  '10.00 kg',
  'Sofa cum bed in Ocean Weave fabric.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  54999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/opUJ_IIElM-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/YgEcLgE_3Q-2.png',
  'https://www.urbanladder.com/product/peckham-sofa-cum-bed-in-ocean-weave-9283852'
),
(
  'Zehnloch 3 Seater Click Clack Sofa cum Bed In Glacier Blue Colour',
  'Urban Ladder',
  'Glacier Blue',
  12,
  NULL,
  '89.90 cm',
  '1.80 m',
  '81.30 cm',
  '43.75 kg',
  'Sofa cum bed in Glacier Blue fabric.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  14999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Im6zeiAJvG-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/4KHpeohxeb-2.png',
  'https://www.urbanladder.com/product/zehnloch-3-seater-click-clack-sofa-cum-bed-in-glacier-blue-colour-7518895-8687476'
),
(
  'Salford 3 Seater Click Clack Sofa Cum Bed In Baltic Blue Colour',
  'Urban Ladder',
  'Baltic Blue',
  12,
  NULL,
  '78.00 cm',
  '2.04 m',
  '89.90 cm',
  '66.00 kg',
  'Designed for modern living, the Salford sofa bed brings effortless style and smart functionality together. Its grid-tufted backrest and plush armrests create a clean, contemporary silhouette. With a simple click-clack mechanism, it transforms from a sophisticated sofa to a cosy bed in seconds. Beneath, hidden storage offers space for extra linens, throws, or cushions. Upholstered in premium fabric. Rubberwood legs in dark walnut finish. Available in 4 options: Baltic Blue, Vapur Grey, Moss Green and Ochre.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  32999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DvL84T2Nlr-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sLnVEHa7Sk-2.png',
  'https://www.urbanladder.com/product/salford-sofa-cum-beds-in-baltic-blue-9292973'
),
(
  'Kowloon Sectional 3 Seater Pull Out Sofa cum Bed In Daschund Brown Colour',
  'Urban Ladder',
  'Daschund Brown',
  12,
  NULL,
  '1.66 m',
  '2.25 m',
  '90.00 cm',
  '70.50 kg',
  'A cozy spot for movie nights, and a guest room in disguise for unexpected overnight stays. The Kowloon Sofa-Cum-Bed, a sectional that masters the art of transformation. With a simple pull, the base glides open, unveiling a spacious double bed in seconds. The chaise lifts effortlessly, revealing a generous storage compartment. Available in three options: Daschund Brown, Baltic Blue in Premium Chenille Fabric and Urban Grey in Premium Chenille Fabric. Indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  49999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IguucomcHw-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IrrtIk8M8-2.png',
  'https://www.urbanladder.com/product/kowloon-sectional-3-seater-pull-out-sofa-cum-bed-in-daschund-brown-colour-7518884-8687463'
),
(
  'Camden 3 Seater Pull Out Sofa cum Bed In Smoke Grey Colour',
  'Urban Ladder',
  'Smoke Grey',
  12,
  NULL,
  '1.99 m',
  '1.80 m',
  '69.00 cm',
  '104.00 kg',
  'Some pieces do more than just fill a space—they define it. The Camden Sofa-Cum-Bed is one such masterpiece. By day, it''s a refined three-seater. By night, it transforms into a cozy bed in just three simple steps. Camden''s smooth pull-out mechanism ensures a hassle-free transition. Available in five options: Smoke Grey, Salsa Red, Vapour Grey, Mocha Brown and Jade Blue. 3-seater configuration. Indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  39999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/U28YPuC-Fv-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/H1CTfahc6H-2.jpg',
  'https://www.urbanladder.com/product/camden-3-seater-pull-out-sofa-cum-bed-in-smoke-grey-colour-7518901-8687483'
),
(
  'Felicity 3 Seater Click Clack Sofa cum Bed In Graphite Grey Colour',
  'Urban Ladder',
  'Graphite Grey',
  12,
  NULL,
  '81.30 cm',
  '1.99 m',
  '84.50 cm',
  '59.00 kg',
  'Plush and comfy, the Felicity is every insomniac''s dream come true. A gentle push turns it into an inviting single bed. Made of eucalyptus wood. Foam cushioning. Fabric upholstery. The click-clack mechanism for ease of use.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  24999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-7dF_VFu3r-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/1XCNG2CXxf-2.png',
  'https://www.urbanladder.com/product/felicity-3-seater-click-clack-sofa-cum-bed-in-graphite-grey-colour-7518894-8687487'
),
(
  'Palermo 3 Seater Click Clack Sofa cum Bed In Olive Green Colour',
  'Urban Ladder',
  'Olive Green',
  12,
  NULL,
  '1.23 m',
  '1.87 m',
  '40.80 cm',
  '65.35 kg',
  'A fabric 3 seater sofa bed that transforms to a twin bed. The internal click-clack mechanism allows an instant conversion from sofa to bed. The plush cushions make it extremely soft and comfortable in either form. For indoor use only.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  24999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/84lSCC91_a-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qSqbXqhxVN-2.jpg',
  'https://www.urbanladder.com/product/palermo-3-seater-click-clack-sofa-cum-bed-in-olive-green-colour-7518904-8687505'
),
(
  'Peckham 3 Seater Click Clack Sofa Cum Bed In Granite Weave Colour',
  'Urban Ladder',
  'Granite Weave',
  12,
  NULL,
  '1.39 m',
  '2.04 m',
  '78.00 cm',
  '10.00 kg',
  'Sofa cum bed in Granite Weave fabric.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  54999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/bldGwCTaxd-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/T5Znp2m8h6-2.png',
  'https://www.urbanladder.com/product/peckham-sofa-cum-bed-in-granite-weave-9283850'
),
(
  'Salford 3 Seater Click Clack Sofa Cum Bed In Ochre Colour',
  'Urban Ladder',
  'Ochre',
  12,
  NULL,
  '78.00 cm',
  '2.04 m',
  '89.90 cm',
  '66.00 kg',
  'Designed for modern living, the Salford sofa bed brings effortless style and smart functionality together. With a simple click-clack mechanism, it transforms from a sophisticated sofa to a cosy bed in seconds. Available in 4 options: Baltic Blue, Vapur Grey, Moss Green and Ochre.',
  NULL,
  'Fabric',
  NULL,
  NULL,
  '3 Seater',
  NULL,
  32999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/QS6E_waIpI-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZGtDXZ8le-b.jpg',
  'https://www.urbanladder.com/product/salford-sofa-cum-beds-in-ochre-9292975'
),
(
  'Emma Diwan in Teak Finish with Macadamia Brown Fabric Colour',
  'Urban Ladder',
  'Macadamia Brown',
  36,
  NULL,
  '88.50 cm',
  '1.91 m',
  '76.00 cm',
  '62.90 kg',
  'Earthy beauty, divine comfort. The Emma day bed can effortlessly shift from a sofa during the AM to a bed in the PM. An elegant mid-high slatted backrest is balanced off by rounded bolsters, making it the perfect addition to a family living room or guest bedroom. Made from Sheesham Wood. Avoid exposure to direct sunlight.',
  NULL,
  'Solid Wood',
  NULL,
  NULL,
  NULL,
  NULL,
  28999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/JujUROFtGD-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nabEXfEXdv-1.jpg',
  'https://www.urbanladder.com/product/emma-diwan-in-macadamia-brown-colour-7520718-9420547'
),
(
  'Sigmund Diwan in Cloud Burst Grey Colour',
  'Urban Ladder',
  'Cloud Burst Grey',
  36,
  NULL,
  '76.00 cm',
  '1.72 m',
  '70.00 cm',
  '45.85 kg',
  'Buy Sigmund Diwan in Cloud Burst Grey Colour & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.',
  NULL,
  'Solid Wood',
  NULL,
  NULL,
  NULL,
  NULL,
  19999,
  'https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DGuSPiz15mK-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/j92Ay1JnCdC-1.jpg',
  'https://www.urbanladder.com/product/sigmund-diwan-in-cloud-burst-grey-colour-7520706'
);
