-- Urban Ladder sofa / recliner / sofa-cum-bed catalog (bulk import).
-- Adds category column if missing, replaces existing rows with matching product_url.

ALTER TABLE sofa_products ADD COLUMN IF NOT EXISTS category text;

DELETE FROM sofa_products WHERE product_url IN ('https://www.urbanladder.com/product/vetra-3-seater-leather-sofa-in-olive-9227440',
  'https://www.urbanladder.com/product/apollo-compact-3-seater-fabric-sofa-9552548',
  'https://www.urbanladder.com/product/ronan-3-seater-fabric-sofa-in-rust-colour-9106256',
  'https://www.urbanladder.com/product/taran-teak-wood-sofa-deep-olive-velvet-8281294',
  'https://www.urbanladder.com/product/raynor-3-seater-wooden-sofa-finish-amber-walnut-fabric-macadamia-brown-8115797',
  'https://www.urbanladder.com/product/liverpool-2-seater-fabric-sofa-in-blue-colour-9481315',
  'https://www.urbanladder.com/product/waverly-3-seater-leather-sofa-in-apricot-9301484',
  'https://www.urbanladder.com/product/chelsea-sectional-fabric-sofa-dachshund-brown-7520558',
  'https://www.urbanladder.com/product/luna-3-seater-fabric-sofa-slate-grey-7520535-9420804',
  'https://www.urbanladder.com/product/emila-3-seater-fabric-sofa-in-fossil-weave-colour-9071574',
  'https://www.urbanladder.com/product/granada-essential-3-seater-fabric-sofa-in-moss-green-8361261',
  'https://www.urbanladder.com/product/ezra-3-seater-sofa-in-desert-sand-fabric-9264833',
  'https://www.urbanladder.com/product/leeroy-leather-three-seater-motorized-recliner-in-hazelnut-tan-9684734',
  'https://www.urbanladder.com/product/emila-fabric-three-seater-motorized-recliner-in-fossil-weave-colour-9771318',
  'https://www.urbanladder.com/product/dawson-fabric-one-seater-manual-recliner-in-coastal-blue-colour-7520169-8720972',
  'https://www.urbanladder.com/product/lebowski-fabric-one-seater-manual-recliner-in-cobalt-fabric-colour-7520195-8720973',
  'https://www.urbanladder.com/product/atticus-single-seater-swivel-rock-recliner-7520184-8721040',
  'https://www.urbanladder.com/product/marvin-entertainment-recliner-in-beige-8144342',
  'https://www.urbanladder.com/product/griffin-fabric-one-seater-manual-recliner-in-lapis-blue-fabric-colour-7520212-8721003',
  'https://www.urbanladder.com/product/emila-fabric-two-seater-motorized-recliner-in-blue-colour-7520163-8721017',
  'https://www.urbanladder.com/product/raphael-leatherette-two-seater-manual-recliner-in-off-white-colour-7520205-8721022',
  'https://www.urbanladder.com/product/bernice-one-seater-recliner-in-tan-colour-7520196-8720986',
  'https://www.urbanladder.com/product/mohave-leather-recliner-8294279',
  'https://www.urbanladder.com/product/marlowe-single-seater-motorised-recliner-in-ancient-ivory-cream-leatherette-8144340',
  'https://www.urbanladder.com/product/kowloon-sectional-sofa-cum-bed-with-storage-colour-baltic-blue-premium-chenille-8115729-8384539-8687503',
  'https://www.urbanladder.com/product/felicity-3-seater-click-clack-sofa-cum-bed-in-olive-green-colour-7518906-8687510',
  'https://www.urbanladder.com/product/palermo-3-seater-click-clack-sofa-cum-bed-in-midnight-indigo-blue-colour-7518902-8687574',
  'https://www.urbanladder.com/product/camden-3-seater-pull-out-sofa-cum-bed-in-smoke-grey-colour-7518901-8687483',
  'https://www.urbanladder.com/product/peckham-sofa-cum-bed-in-granite-weave-9283850',
  'https://www.urbanladder.com/product/salford-sofa-cum-beds-in-moss-green-9292974',
  'https://www.urbanladder.com/product/zehnloch-3-seater-click-clack-sofa-cum-bed-in-glacier-blue-colour-7518895-8687476',
  'https://www.urbanladder.com/product/kowloon-sectional-3-seater-pull-out-sofa-cum-bed-in-daschund-brown-colour-7518884-8687463',
  'https://www.urbanladder.com/product/camden-compact-3-seater-pull-out-sofa-cum-bed-in-mocha-brown-colour-7518898-8687479',
  'https://www.urbanladder.com/product/peckham-sofa-cum-bed-in-oyster-beige-9283851',
  'https://www.urbanladder.com/product/palermo-3-seater-click-clack-sofa-cum-bed-in-olive-green-colour-7518904-8687505',
  'https://www.urbanladder.com/product/felicity-3-seater-sofa-cum-bed-in-midnight-indigo-blue-colour-7518886-8687474');

INSERT INTO sofa_products (
  category,
  name,
  brand,
  colour,
  warranty_in_months,
  length,
  width,
  height,
  net_weight,
  description,
  generic_name,
  primary_material_type,
  primary_material_subtype,
  primary_room,
  seating_capacity,
  product_model_name,
  price,
  images_url,
  product_url
) VALUES
($d$Collection / Sofa Sets$d$,
  $d$Vetra 3 Seater Leather Sofa In Olive Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  12,
  $d$94$d$,
  $d$2$d$,
  $d$88$d$,
  $d$60.00 kg$d$,
  $d$Vetra balances modern minimalism with plush, inviting comfort. Its streamlined silhouette and angled armrests create an elegant presence, while stitched back cushions add a textured detail that captivates the eye. Upholstered in smooth, premium leather, the sofa develops a natural patina over time that enriches its character. Elevated on dark chrome-finished legs, it brings a sense of lightness while grounding your living room. Perfect for urban and minimalist interiors, the Vetra sofa turns every space into a statement. - Available in three colour options: Olive, White and Wine. - Available in 1, 2 and 3 seater options. - Dark chrome-finished metal legs.$d$,
  NULL,
  $d$Leather$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  89999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/uCtAB2Irm4-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Qyl4NG3K2g-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JyiJu7kQz4-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gql5XkeVq-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_aVgmYQIKX-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/RFf9EMOZv9-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/2rAc27kpB-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MXZxChiQwm-g.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/uCtAB2Irm4-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Qyl4NG3K2g-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/46bLmp5zUi-b.jpg$d$,
  'https://www.urbanladder.com/product/vetra-3-seater-leather-sofa-in-olive-9227440'),
($d$Collection / Sofa Sets$d$,
  $d$Apollo Compact 3 Seater  Fabric Sofa In Lapis Blue Colour - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$Fabric Options : Premium Cushion Type : Soft Qty : 1$d$,
  36,
  $d$1$d$,
  $d$85$d$,
  $d$81$d$,
  $d$0.04 kg$d$,
  $d$Seasoned solid wood frames This sofa’s frame is made from seasoned solid wood that undergoes a 3-step treatment for protection against borers and is kiln-dried for moisture control. High-performance fabric The upholstery comes with a high rub count and is resistant to fading and pilling. Its durable properties will keep your sofa looking new for years to come. Long-lasting suspension system This sofa is supported on a foundation of 3 inch wide elastic bands, thicker and more durable than the industry standard. Anti-sag construction This sofa is designed to combat sagging. The multi-density foam in the seat cushions reduces sagging due to prolonged use. A grid of polyfill pockets in the back cushions prevents the cushions from weighing down because of gravity.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  41359.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-1LHVlXKyb-0.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/QLTxXZirXqF-00-(1).png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ILaKbAWm_TV-02.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IKix75f5zvJ-03.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/taMs1rCBrdM-08.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/AHO40C4LyPD-06.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/vHj7oiAUVew-09.png$d$,
  'https://www.urbanladder.com/product/apollo-compact-3-seater-fabric-sofa-9552548'),
($d$Collection / Sofa Sets$d$,
  $d$Ronan 3 Seater Fabric Sofa In Rust Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  12,
  $d$95$d$,
  $d$2$d$,
  $d$93$d$,
  $d$53.00 kg$d$,
  $d$Generously proportioned and effortlessly inviting, the Ronan sofa turns everyday seating into a moment of indulgence. Its high back offers plush support while framing the sofa’s commanding silhouette. Deep seats and broad, embracing arms invite you to sink in, linger, and let the day melt away. Wrapped in warm fabric, Ronan radiates sophistication, while the solid wood accent elevates its timeless appeal. With ground clearance for easy cleaning, every day begins and ends in effortless comfort. - High-back design. - Available in Beige and Rust colour options. - Upholstered in performance fabric: resistant to stains and water, safe for pets, and non-toxic. - Available in 1, 2 and 3 seater options.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  49999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/cGE8aOoVjW-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bEAi0mdrqS-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YFfVky-8fY-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/PpzMjW5U2-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ylu9NYAQSQ-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ccVKEZuXK3-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/kpXcdUfBt-g.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/cGE8aOoVjW-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/MblbxZUD2-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/46bLmp5zUi-b.jpg$d$,
  'https://www.urbanladder.com/product/ronan-3-seater-fabric-sofa-in-rust-colour-9106256'),
($d$Collection / Sofa Sets$d$,
  $d$Taran 3 Seater Wooden Sofa in Deep Olive Velvet Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  36,
  $d$1$d$,
  $d$74$d$,
  $d$80$d$,
  $d$45.00 kg$d$,
  $d$A Sofa That Feels Like a Warm Embrace. Crafted with timeless elegance, this sofa seamlessly blends Indian craftsmanship with modern sensibilities. Designed to be both an accent and a primary piece, its solid Indian teak wood frame—finished in a rich sienna teak—exudes warmth, strength, and style. The curved armrests and backrest sculpt a silhouette that invites you to sink in, while the cane accent adds a touch of artisanal charm. Upholstered in premium solid and printed fabrics, this piece offers a plush, curl-up-comfy experience. The brass-finished metal caps on the legs lend a sophisticated edge, elevating its transitional modern aesthetic. Redefine your space with the enduring charm of Taran. Indian teak wood ensures high durability and natural resistance to water and weathering. Three-layer PU foam in the seat offers superior support, pressure relief, and bounce-back comfort. Double side diamond-patterned cane accents add durability. Polyfill backrest provides a cloud-like, airy feel. Available in three premium fabrics: Deep Olive Velvet , Natural Herringbone , and Sunset Ikat Stripes . Available in 1-seater , 2-seater , and 3-seater configurations.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  64999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LI_jEx8IHH-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/SF_62BR2_J-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7Qiag4CJn6-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/SMnJOGQqAp-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gHCrZkSS5-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7o6dcsaige-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9MOxthAgmx-g.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/mGf3pZIQKy-h.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/LI_jEx8IHH-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/sIrxyeeBL-1.jpg$d$,
  'https://www.urbanladder.com/product/taran-teak-wood-sofa-deep-olive-velvet-8281294'),
($d$Collection / Sofa Sets$d$,
  $d$Raynor 3 Seater Wooden Sofa in Macadamia Brown Colour - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  12,
  $d$1$d$,
  $d$78$d$,
  $d$81$d$,
  $d$51.00 kg$d$,
  $d$Returns Quality Promise

Buy Raynor 3 seater wooden sofa, Finish- Amber Walnut, Fabric- Macadamia Brown & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  32999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/BQcbvOe01i-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UoeX4EGVyG-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Wr832cUka-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/C1WAYzmNK9-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/B801C-kA7s-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/NxFdsug_Wz-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/bC5xomMrS-g.png$d$,
  'https://www.urbanladder.com/product/raynor-3-seater-wooden-sofa-finish-amber-walnut-fabric-macadamia-brown-8115797'),
($d$Collection / Sofa Sets$d$,
  $d$Liverpool 2 Seater Fabric Sofa in Blue Colour - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$76$d$,
  $d$1$d$,
  $d$80$d$,
  $d$26.40 kg$d$,
  $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$2 Seater$d$,
  NULL,
  9999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/6FI-4icxt-Liverpool-2-Seater-Fabric-Sofa-in-Blue-Colour.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Z87Lksuqu-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/CIQ8wCSmla-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/KwsSBJbAI3-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/6dbQ_ngZQX-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3yLUacYrh-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XGzqQCFeYj-f.jpg$d$,
  'https://www.urbanladder.com/product/liverpool-2-seater-fabric-sofa-in-blue-colour-9481315'),
($d$Collection / Sofa Sets$d$,
  $d$Waverly 3 Seater Leather Sofa in Apricot Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  12,
  $d$85$d$,
  $d$2$d$,
  $d$80$d$,
  $d$78.00 kg$d$,
  $d$Capturing the essence of mid-century charm, the Waverly sofa in premium leather exudes timeless sophistication. Rounded corners and soft contours lend a gentle warmth, while elevated wooden legs keep the silhouette light and grounded. Sink in and feel the comfort of its curved armrests, designed to make every moment of lounging effortlessly relaxing. The classic biscuit tufting along the backrest adds rich texture and visual depth. Whether styled in a contemporary home or paired with retro accents, Waverly brings effortless balance, ease, and elegance to your space. - Upholstered in premium leather. - Available in Army Green, Apricot colour options. - Available in 1, 2 and 3 seater configurations.$d$,
  NULL,
  $d$Leather$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  66999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/wU4sF67mLG-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Cux99YSWsh-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/O1LugxpA2k-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/af2WdCqN5-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/njlOUS_jv8-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9ONinKRETZ-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gaDtohGR9W-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/wU4sF67mLG-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Cux99YSWsh-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/1-wOGKL24m-3.jpg$d$,
  'https://www.urbanladder.com/product/waverly-3-seater-leather-sofa-in-apricot-9301484'),
($d$Collection / Sofa Sets$d$,
  $d$Chelsea Left Aligned 3 Seater Sectional Fabric Sofa in Daschund Brown Colour - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : Left Aligned 3-Seater Qty : 1$d$,
  12,
  $d$1$d$,
  $d$2$d$,
  $d$75$d$,
  $d$46.00 kg$d$,
  $d$Buy Chelsea Left Aligned 3-Seater Fabric Sofa (Daschund Brown) & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  59999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/M2T7rNMAQJ-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nzHZBZrOPv-a.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_5O3mSWBM0-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nQQYAlJJOk-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/LmJYuUCUuE-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/dinyRvZDJr-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/bwW7z8hmwU-g.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/o5pCDeJhv-h.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/bz5ZGFpZr-Chelsea-Left-Aligned-3-Seater-Sectional-Fabric-Sofa-in-Daschund-Brown-Colour.png$d$,
  'https://www.urbanladder.com/product/chelsea-sectional-fabric-sofa-dachshund-brown-7520558'),
($d$Collection / Sofa Sets$d$,
  $d$Luna 3 Seater Fabric Sofa in Slate Grey Colour - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  12,
  $d$83$d$,
  $d$1$d$,
  $d$86$d$,
  $d$50.00 kg$d$,
  $d$Urban Ladder Home Decor Solutions Private Limited, Block C & D, Plot No. 1, 2nd Phase,Industrial Area, Sector - Bidadi,Bangalore-562109$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  18999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/NlvYbbBM7tu-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/98F5-CagHJB-a.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/YYJVk0g5yJ7-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/wszVSfgzpg6-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/EpVDHBb9Mca-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/tX4QgIavOJP-f.png$d$,
  'https://www.urbanladder.com/product/luna-3-seater-fabric-sofa-slate-grey-7520535-9420804'),
($d$Collection / Sofa Sets$d$,
  $d$Emila 3 Seater Fabric Sofa In Fossil Weave Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  12,
  $d$96$d$,
  $d$2$d$,
  $d$1$d$,
  $d$75.00 kg$d$,
  $d$Everyday lounging transforms into a ritual with the Emila sofa. Every detail is designed for effortless indulgence—deep-cushioned seats, plush armrests, and supportive headrests invite you to sink in and lose track of time. The soft, inviting upholstery cocoons you in comfort, making every moment feel serene. Sleek stainless steel legs add a contemporary edge, seamlessly lifting the sofa’s presence in your living space. More than just a spot to sit, the Emila sofa is a timeless retreat. - Available in 1-, 2- and 3-seater options. - Available in Amber Weave and Fossil Weave colour options.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  69999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Uym4w6BgF_-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/yY-duiFOTM-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bdl0g3Djcm-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/utAId_BRV-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/QQa8QiIN0t-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/dkSBqPl-jX-h.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/iKfUtb0KT-i.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Uym4w6BgF_-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/86RkhBhBo-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/0U3YNx-1mE-b.jpg$d$,
  'https://www.urbanladder.com/product/emila-3-seater-fabric-sofa-in-fossil-weave-colour-9071574'),
($d$Collection / Sofa Sets$d$,
  $d$Granada Essential 3 Seater Fabric Sofa In Moss Green Colour - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  36,
  $d$2$d$,
  $d$87$d$,
  $d$82$d$,
  $d$46.00 kg$d$,
  $d$Urban Ladder Home Decor Solutions Private Limited, Block C & D, Plot No. 1, 2nd Phase,Industrial Area, Sector - Bidadi,Bangalore-562109$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  52799.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qtipnrLCb-Granada-Essential-3-Seater-Fabric-Sofa-In-Moss-Green-Colour.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IPUtxJXsZd-02.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/spET0GE0CG-00.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3YRKlnlYH-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/4pot_C6CJY-03.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/YYhKUbsACo-04.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/WdaZ_9htME-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sqiwq4Zq4-07.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/w8GW3AvJo-Granada-Essential-3-Seater-Fabric-Sofa-In-Dark-Coral.png$d$,
  'https://www.urbanladder.com/product/granada-essential-3-seater-fabric-sofa-in-moss-green-8361261'),
($d$Collection / Sofa Sets$d$,
  $d$Ezra 3 Seater Sofa in Desert Sand Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  24,
  $d$1$d$,
  $d$2$d$,
  $d$75$d$,
  $d$86.00 kg$d$,
  $d$Sculptural and endlessly inviting, the Ezra sofa brings together modern form and pure comfort. Its wide arms and deep seating create a lounge-like experience, perfect for sinking in after a long day. Inspired by the soft, organic rhythm of a caterpillar’s form, the segmented upholstery adds a cocooning rhythm to its silhouette. Plush cushions and a low profile offer exceptional comfort, while the cosy pillow armrests complete its enveloping feel. Ezra blends seamlessly into contemporary spaces — a statement of calm sophistication and everyday luxury. - Available in Sapphire and Desert Sand options. - Rubberwood spherical legs. - Comes with an additional lumber and accent cushions for additional comfort. - Available in 2 and 3 seater configuration.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  89999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/BINnq06LWN-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/t-oEmMsuQ-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/PWQEw2swjc-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/6WV5Uv9h-Y-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fYfcqBt4w-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/OKitfFIEev-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0Q7zqDbXap-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/BINnq06LWN-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/t-oEmMsuQ-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/SoCUpl026h-b.jpg$d$,
  'https://www.urbanladder.com/product/ezra-3-seater-sofa-in-desert-sand-fabric-9264833'),
($d$Collection / Recliners$d$,
  $d$Leeroy Leather Three Seater Motorized Recliner in Hazelnut Tan - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$leather options: Marigold and Oyster White</li><li>Available in 3 configurations: 3-seater$d$,
  24,
  $d$95$d$,
  $d$2$d$,
  $d$1$d$,
  $d$164.00 kg$d$,
  $d$Imagine a world where time itself slows as you sink into a plush embrace. Each moment feels like drifting on a cloud, enveloped in the gentle luxury of Leeroy. Zero Gravity System Modelled after the posture of astronauts during space missions, the zero gravity system creates a sensation of weightlessness, allowing you to float effortlessly in a perfect position. By aligning your heart and feet at the same level, this system evenly distributes your body weight for optimal blood circulation. Triple Power Function Equipped with a high-quality motor and sleek controls, you can fine-tune your comfort with the triple power reclining function. Independent control of the lumbar support, backrest, and footrest provides customised support, making it perfect for extended sessions of lounging. Luxury Leather Upholstery Crafted from luxurious natural top-grain leather, Leeroy provides a sophisticated aesthetic and long-lasting comfort, making it a standout piece in any contemporary setting. Easy-to-use controls and a high-grade electric motor Available in two colour leather options: Marigold and Oyster White Available in 3 configurations: 3-seater, 2-seater, and 1-seater Oasis Collection$d$,
  NULL,
  $d$Leather$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  199999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/dO3zN_3gU-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/OVnr-S-7I-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/zSMtaP9npr-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_PkXoJUhS6-d1.gif | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/32TSo92A7w-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/4cP9f6Woys-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/osrIw8ny1S-g.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/vKVDIEsPx-i.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DPgtMLB7zC-j.png$d$,
  'https://www.urbanladder.com/product/leeroy-leather-three-seater-motorized-recliner-in-hazelnut-tan-9684734'),
($d$Collection / Recliners$d$,
  $d$Emila Fabric Three Seater Motorized Recliner in Fossil Weave Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 3 Seater Qty : 1$d$,
  12,
  $d$99$d$,
  $d$2$d$,
  $d$96$d$,
  $d$132.00 kg$d$,
  $d$Everyday lounging transforms into a ritual with the Emila recliner sofa. Every detail is designed for effortless indulgence—deep-cushioned seats, plush armrests, and supportive headrests invite you to sink in and savour unhurried moments. The soft, inviting upholstery cocoons you in comfort, making every moment feel serene. Sleek stainless steel legs add a contemporary edge, seamlessly lifting the sofa’s presence in your living space. More than just a spot to sit, Emila is a timeless retreat. - Available in 1-, 2- and 3-seater options. - Available in Amber Weave, Blue, Cream, Grey and Fossil Weave colour options.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  89999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/yeUXjiMgK-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Vm7s38N26O-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/C8-upe8cYV-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-S8fMOwUB8-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gdC5c-FNL-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/HmJhP2eJO0-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/sffSh9NSH-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Qkq0JG2OCV-g.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-8OKkvMJt5-h.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Y0UIgN-8g-i.png$d$,
  'https://www.urbanladder.com/product/emila-fabric-three-seater-motorized-recliner-in-fossil-weave-colour-9771318'),
($d$Collection / Recliners$d$,
  $d$Dawson Fabric One Seater Manual Recliner in Coastal Blue Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$83$d$,
  $d$92$d$,
  $d$1$d$,
  $d$40.00 kg$d$,
  $d$Dawson Single Seater Entertainment Recliner– where style meets comfort for your ultimate relaxation experience. This modern recliner is designed with both aesthetics and functionality in mind, making it a perfect addition to your living room, home theater, or entertainment space. Sink into luxurious comfort as you recline in the Dawson Single Seater. Keep your favorite beverages within reach, making movie nights and gaming sessions more enjoyable than ever. Please refer to images for dimension details For indoor use only$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$1 Seater$d$,
  NULL,
  18999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/XsW1ZxgfU2-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/npCycrJTpA-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/k-EPF1AuS--3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/SQFlGGjI6Q-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/aLDAHBp8Qf-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/py4TbKaWkf-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9RrQLVFC6h-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9ZBfV5VjX2-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XsW1ZxgfU2-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/npCycrJTpA-2.jpg$d$,
  'https://www.urbanladder.com/product/dawson-fabric-one-seater-manual-recliner-in-coastal-blue-colour-7520169-8720972'),
($d$Collection / Recliners$d$,
  $d$Lebowski Fabric One Seater Manual Recliner in Cobalt Fabric Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 1 Seater Qty : 1$d$,
  12,
  $d$81$d$,
  $d$92$d$,
  $d$1$d$,
  $d$45.15 kg$d$,
  $d$Some moments deserve to be savoured—whether it is curling up with a book, sinking into your favourite show, or indulging in a well-earned nap. The Lebowski recliner is designed for just that. With its plush upholstery and inviting silhouette, this recliner sofa transforms any corner of your home into a sanctuary of relaxation. The manual reclining mechanism allows you to adjust your position with a simple pull, while the generously padded backrest and seat cushions provide exceptional support. Crafted for durability, each seat has been rigorously tested to support up to 140 kg. Extremely versatile, Lebowski recliner sofa can be placed in your living room or bedroom for ultimate comfort. - This recliner sofa is available in single-seater, two-seater, and three-seater configurations. - Choose from leatherette and fabric upholstery. - Please refer to the images for dimension details. - Indoor use only.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$1 Seater$d$,
  NULL,
  16999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/o7IZQrlbbu-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/q5Gp5gs77L-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YiIULGPDLa-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/aI9TZG6T7e-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/jJOtqniDID-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/yVtyGKE7V9p-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Q9ntrpubFp8-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7Obg7koMxhy-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/o7IZQrlbbu-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/9GH0u4YE-mB-2.jpg$d$,
  'https://www.urbanladder.com/product/lebowski-fabric-one-seater-manual-recliner-in-cobalt-fabric-colour-7520195-8720973'),
($d$Collection / Recliners$d$,
  $d$Atticus Single Seater Swivel Rock Recliner in Urban Grey Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$1$d$,
  $d$1$d$,
  $d$1$d$,
  $d$30.00 kg$d$,
  $d$Experience premium comfort and versatility with the Atticus Single-Seater Recliner. Wrapped in plush fabric, this contemporary recliner brings both style and advanced functionality to your living space. Its innovative swivel capability gives you the freedom to shift your focus without having to reposition the entire recliner. The gentle rocking motion adds another dimension of relaxation, perfect for unwinding after a long day or creating a soothing environment for reading or napping. Generously padded headrest, armrests and backrest offer exceptional seating experience for extended periods of use. Perfect for modern living rooms, home theaters, or creating a dedicated relaxation corner, the Atticus recliner sofa combines functionality with refined aesthetics. - Available in both motorized and manual reclining mechanisms for customised comfort. - The motorised recliner features a 270-degree swivel while the manual recliner offers a 360-degree swivel. - Available in three colour options: Urban Grey, Baltic Blue and Shitake Beige. - Please refer to the images for dimension details. - Indoor use only.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$1 Seater$d$,
  NULL,
  27999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/6zGKBlWelce-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/h2b3ZVvZKfP-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9ohNzjinR3M-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JS-c0nP_yD7-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/A5O8rU_okHv-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/V1J_6SgjE_Z-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/55zQcWjUU-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/CoGMj-arHB-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/6zGKBlWelce-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/-bQP8daY5F-2.jpg$d$,
  'https://www.urbanladder.com/product/atticus-single-seater-swivel-rock-recliner-7520184-8721040'),
($d$Collection / Recliners$d$,
  $d$Marvin Entertainment Recliner in Beige Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  24,
  $d$2$d$,
  $d$90$d$,
  $d$95$d$,
  $d$146.00 kg$d$,
  $d$Buy Marvin Entertainment Recliner in Beige & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  79999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_-omLxkf9-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ZlyUH4rE6s-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/smgYHgQKO4-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/pXJxyQv7fW-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/3OVPPhCCtD-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TWu1hcCr2T-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/vYHF_w9iWE-g.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/OXol1-g2o-h.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/oWCqr0zqJP-i.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ukBIwdp3my-j.png$d$,
  'https://www.urbanladder.com/product/marvin-entertainment-recliner-in-beige-8144342'),
($d$Collection / Recliners$d$,
  $d$Griffin Fabric One Seater Manual Recliner in Lapis Blue Fabric Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 1 Seater Qty : 1$d$,
  12,
  $d$93$d$,
  $d$96$d$,
  $d$98$d$,
  $d$50.80 kg$d$,
  $d$Poised and plush. With a generously cushioned body and a classic shape, Griffin recliner is a seat treat. Covered in premium upholstery, the recliner mechanism allows you to lean almost 180 degrees back and also unfolds with a footprint, giving you maximum comfort. Add this to your living or bedroom spaces for a contemporary inviting appeal. Choose from leatherette or fabric upholstery Please refer to the images for dimension details Worry-free! We have tested our recliners for 25,000 cycles - this means you can use it for 15-20 years without a second thought. Rest assured. Our recliners have passed load-bearing capacity testing for up to 140kg, on each seat. Indoor use only$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$1 Seater$d$,
  NULL,
  21999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/tzNTKDW4H7v-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/EbkwCO19Uni-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/T6cojYPl5pg-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/dpe2VUX2MQr-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/s9gnombJYuj-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MVgkaYsfzzD-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/docOOY6hyVd-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7aKLFA9Tsh8-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/tzNTKDW4H7v-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/4PCf7Gs-B6m-2.jpg$d$,
  'https://www.urbanladder.com/product/griffin-fabric-one-seater-manual-recliner-in-lapis-blue-fabric-colour-7520212-8721003'),
($d$Collection / Recliners$d$,
  $d$Emila Fabric Two Seater Motorized Recliner in Blue Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 2 Seater Qty : 1$d$,
  12,
  $d$96$d$,
  $d$1$d$,
  $d$99$d$,
  $d$93.80 kg$d$,
  $d$The Emila Recliner transforms everyday lounging into a luxurious ritual. At the push of a button, its motorised recline function eases you into relaxation, adapting seamlessly to your comfort needs. Thoughtfully designed, the backrest glides into position without demanding extra space, making it a perfect fit for any room. Plush armrests, headrests, and deep-cushioned seats invite you to sink in and unwind. Beyond indulgence, Emila understands the little luxuries that make a difference. A discreet button console with a built-in USB port keeps your devices charged, while sleek stainless steel legs add a contemporary touch. Wrapped in soft, inviting fabric, this recliner is more than just a seat—it is a retreat. - Available in 1-seater, 2-seater and 3-seater options. - Available in Blue, Grey and Cream colour options. - Please note that only the seats on the two ends recline for the 3 seater. - Please refer to images for dimension details. Indoor use only.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$2 Seater$d$,
  NULL,
  84999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_lmDLUekJ8V-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/hQN8XqkGI-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/dtAbzurFRq-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Jh6JD2fHmO-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-8u_ABwret-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ufZ1_GTwF5-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YwKwbVr_2r-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0XrqHPEaaH-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_lmDLUekJ8V-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/hQN8XqkGI-2.jpg$d$,
  'https://www.urbanladder.com/product/emila-fabric-two-seater-motorized-recliner-in-blue-colour-7520163-8721017'),
($d$Collection / Recliners$d$,
  $d$Raphael Leatherette Two Seater Manual Recliner in Off White Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 2 Seater Qty : 1$d$,
  12,
  $d$1$d$,
  $d$1$d$,
  $d$99$d$,
  $d$81.70 kg$d$,
  $d$Lounge like you mean it. Snuggle up in the plush cushioning of our Raphael 2 Seater Recliner. A perfect blend of style and functionality, this transitional style 3 position manual recliner comes with a smooth glide mechanism, puffed armrests and a cushioned headrest that will help you relax and stretch in comfort.$d$,
  NULL,
  $d$Leatherette$d$,
  NULL,
  NULL,
  $d$2 Seater$d$,
  NULL,
  34999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/IH42XHBnzBm-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/m6Dx6CNpI9j-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/zFGphz7ZVKq-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_vjS3N4x_hS-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_ydQxjUyVTS-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/pa8dRXR7ETJ-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-WmLnaYj0XW-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9LHOzc7h-zG-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IH42XHBnzBm-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/SvVvG2mtCt-2.jpg$d$,
  'https://www.urbanladder.com/product/raphael-leatherette-two-seater-manual-recliner-in-off-white-colour-7520205-8721022'),
($d$Collection / Recliners$d$,
  $d$Bernice One Seater Recliner in Tan Colour$d$,
  $d$Urban Ladder$d$,
  $d$Seating Capacity : 1 Seater Qty : 1$d$,
  12,
  $d$93$d$,
  $d$1$d$,
  $d$99$d$,
  $d$29.00 kg$d$,
  $d$Lounge like you mean it. Snuggle up in the plush cushioning of our Bernice 1 Seater Recliner. A perfect blend of style and functionality, this contemporary style 3 position manual recliner comes with a smooth glide mechanism, puffed armrests and a cushioned headrest that will help you relax and stretch in comfort.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$1 Seater$d$,
  NULL,
  23999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nRORdWju_Zl-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ZzxpUfqtEzT-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MEcSlju0KCs-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7sto1mLcus7-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/uBc8dC2SBdS-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/IfxUtV8IkyA-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/I5N_zafVqo1-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nRORdWju_Zl-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/D-rSowAGXIR-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/rd4r5zOqpTw-2.jpg$d$,
  'https://www.urbanladder.com/product/bernice-one-seater-recliner-in-tan-colour-7520196-8720986'),
($d$Collection / Recliners$d$,
  $d$Mohave Leather Recliner$d$,
  $d$Urban Ladder$d$,
  $d$Grey$d$,
  12,
  $d$86$d$,
  $d$56$d$,
  $d$1$d$,
  $d$71.20 kg$d$,
  $d$New Century Trading (India) Pvt Ltd, The Centrium, Phoenix Market City, Unit No. 5, 2nd Floor, L.B.S. Road, Kurla (W), Mumbai - 400070$d$,
  NULL,
  $d$Leather$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  69999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MEh_Y1Aten-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/hSXFJT_MFr-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/vsNnLW-GfT-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/qfHSsj1jrS-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/SjerhbDPmoy-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/UflRzhgc9hD-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/t7vev50dImY-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/CGlHYeNGBrj-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/MEh_Y1Aten-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/OaG_jOprVdl-2.jpg$d$,
  'https://www.urbanladder.com/product/mohave-leather-recliner-8294279'),
($d$Collection / Recliners$d$,
  $d$Marlowe Single Seater Motorised Recliner in Ancient Ivory Cream Leatherette Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  24,
  $d$89$d$,
  $d$89$d$,
  $d$98$d$,
  $d$44.00 kg$d$,
  $d$Buy Marlowe Single Seater Motorised Recliner in Ancient Ivory Cream Leatherette & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Leatherette$d$,
  NULL,
  NULL,
  $d$1 Seater$d$,
  NULL,
  29999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/HtVP_ZEa8JV-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0R6Ldpecu85-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/1Gez3rYPTpW-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fKtPP0DqHeF-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Im86cLzTWcj-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/1tlSnnETtQV-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/pW0hrWOUKmO-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/U6xD0X8hQcq-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/HtVP_ZEa8JV-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/0R6Ldpecu85-2.jpg$d$,
  'https://www.urbanladder.com/product/marlowe-single-seater-motorised-recliner-in-ancient-ivory-cream-leatherette-8144340'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Kowloon Sectional Pull Out Sofa Cum Bed with Storage in Baltic Blue Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$2$d$,
  $d$1$d$,
  $d$89$d$,
  $d$71.85 kg$d$,
  $d$A cozy spot for movie nights, and a guest room in disguise for unexpected overnight stays—this is the Kowloon Sofa-Cum-Bed, a sectional that masters the art of transformation. With a simple pull, the base glides open, unveiling a spacious double bed in seconds. The chaise lifts effortlessly, revealing a generous storage compartment to tuck away blankets, pillows, and everyday essentials. Thoughtfully placed side sleeves provide a dedicated home for magazines, newspapers, and more, keeping your living room as organised as it is inviting. Available in chenille fabric options, Kowloon’s plush, velvety texture is irresistibly soft to the touch. Designed to adapt to the rhythm of your life, the Kowloon Sectional Sofa does it all—with effortless style and comfort. - Available in three options: Daschund Brown, Baltic Blue in Premium Chenille Fabric and Urban Grey in Premium Chenille Fabric. - Indoor use only. - Please refer to the images for dimension details.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  44999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/CZpeaJjd5y-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5lybmRpryB-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LLN6ckVoHH-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/tnaQ5iFxgZ-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Y3e3hz3fr-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/XvxlHqyIhV-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/itzJE683io-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/CZpeaJjd5y-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/YCgOUqz8Urd-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/5lybmRpryB-2.png$d$,
  'https://www.urbanladder.com/product/kowloon-sectional-sofa-cum-bed-with-storage-colour-baltic-blue-premium-chenille-8115729-8384539-8687503'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Felicity 3 Seater Click Clack Sofa cum Bed In Olive Green Colour - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$81$d$,
  $d$1$d$,
  $d$84$d$,
  $d$58.65 kg$d$,
  $d$Induces yawns. In a good way. Plush and comfy, the Felicity is every insomniac’s dream come true. A gentle push turns it into an inviting single bed. Perfect for small apartments and sudden guests. Choose from 3 delectable shades. It’ll sit pretty in your living room. Made of eucalyptus wood Foam cushioning Fabric upholstery The yellow and grey variants have a flat weave, while the cream variant has a plush, textured weave. The click-clack mechanism for ease of use Please refer to the images for dimension details$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  24999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/CnkvrmYvDS-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lakeq5ccmQ-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/zqdQwmQ0FP-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/s7BPG5z_ws-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Y77iSVLT7H-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qwpP1JyL3nr-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3E-p7PJvr74-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/9eFoCpD-ekM-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/uBOWtsckGVa-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/vxzTS5RMyxp-9.jpg$d$,
  'https://www.urbanladder.com/product/felicity-3-seater-click-clack-sofa-cum-bed-in-olive-green-colour-7518906-8687510'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Palermo 3 Seater Click Clack Sofa cum Bed In Midnight Indigo Blue Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$1$d$,
  $d$1$d$,
  $d$40$d$,
  $d$60.50 kg$d$,
  $d$Some moments call for conversation, others for quiet relaxation. With the Palermo Sofa-Cum-Bed, you never have to choose. Designed for modern living, this plush three-seater welcomes you with soft fabric and generous cushioning, perfect for unwinding after a long day. When the need arises, it transforms into a cosy twin bed—with a simple click-clack mechanism. Hosting a last-minute guest? Creating a snug nook for a movie marathon? Palermo adapts in an instant, offering the comfort of a bed without compromising on style. Its sleek silhouette and inviting upholstery make it a seamless addition to any space—a true blend of function and finesse. - Available in 3 options: Olive Green, Salsa Red and Midnight Indigo Blue. - Please refer to the images for dimension details. - Indoor use only.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  24999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-kn99h-LC-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-OFidGz23p-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/CmnB_Y9x1q-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/4c78pxNsQw-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/mHk50VDj_r-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/CASHPs0ows-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/mT4Uogjdeg-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FE5FJAiNQT-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-kn99h-LC-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/-OFidGz23p-2.jpg$d$,
  'https://www.urbanladder.com/product/palermo-3-seater-click-clack-sofa-cum-bed-in-midnight-indigo-blue-colour-7518902-8687574'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Camden 3 Seater Pull Out Sofa cum Bed In Smoke Grey Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$1$d$,
  $d$1$d$,
  $d$69$d$,
  $d$104.00 kg$d$,
  $d$Some pieces do more than just fill a space—they define it. The Camden Sofa-Cum-Bed is one such masterpiece. By day, it’s a refined three-seater, effortlessly elevating your living space with its elegant presence. By night, it transforms into a cozy bed in just three simple steps—no fuss, no effort, just comfort on demand. Camden’s smooth pull-out mechanism ensures a hassle-free transition, whether you are hosting overnight or simply unwinding with a book or your favourite show.Thoughtfully designed armrests provide the perfect perch for your elbow, a book, or the TV remote. The Camden Sofa-Cum-Bed makes comfort a way of life. - Available in five options: Smoke Grey, Salsa Red, Vapour Grey, Mocha Brown and Jade Blue. - 3-seater configuration. - Indoor use only. - Please refer to the images for dimension details.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  39999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/U28YPuC-Fv-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/H1CTfahc6H-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/si_qsBt_uM-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/sXHbSykLd7-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/kcQhZEBmHz-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/s6MXFR0tQb-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bpoFUpTChE-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5Xa14H3SoG-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Ij2MdIWjeM-A.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/VUFMTwsl2-A1.jpg$d$,
  'https://www.urbanladder.com/product/camden-3-seater-pull-out-sofa-cum-bed-in-smoke-grey-colour-7518901-8687483'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Peckham 3 Seater Click Clack Sofa Cum Bed In Granite Weave Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$1$d$,
  $d$2$d$,
  $d$78$d$,
  $d$10.00 kg$d$,
  $d$Urban Ladder Home Decor Solutions Private Limited, Block C & D, Plot No. 1, 2nd Phase,Industrial Area, Sector - Bidadi,Bangalore-562109$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  54999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bldGwCTaxd-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/T5Znp2m8h6-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JqFlrkbURV-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/2g2GUhemlg-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0fgIY29UmD-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/2xFY9gjSEt-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JebksicFPy-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5ILcem2NL-8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/bldGwCTaxd-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/T5Znp2m8h6-2.png$d$,
  'https://www.urbanladder.com/product/peckham-sofa-cum-bed-in-granite-weave-9283850'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Salford 3 Seater Click Clack Sofa Cum Bed In Moss Green Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$78$d$,
  $d$2$d$,
  $d$89$d$,
  $d$66.00 kg$d$,
  $d$Designed for modern living, the Salford sofa bed brings effortless style and smart functionality together. Its grid-tufted backrest and plush armrests create a clean, contemporary silhouette that feels right at home in any setting. With a simple click-clack mechanism, it transforms from a sophisticated sofa to a cosy bed in seconds. Beneath, hidden storage offers space for extra linens, throws, or cushions. Perfect for compact rooms and last-minute sleepovers, Salford becomes your go-to spot for effortless relaxation. - Upholstered in premium fabric. - Rubberwood legs in dark walnut finish. - Available in 4 options: Baltic Blue, Vapur Grey, Moss Green and Ochre.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  32999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YZw1YswP4J-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nEVJdCEP5-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/veGiK4rjUS-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9XflcFwm5x-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/iYkNd08fiZ-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/n0zMTBJ2hh-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/UOBn_OBPX1-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/gv9CM4RicL-8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/YZw1YswP4J-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/sLnVEHa7Sk-2.png$d$,
  'https://www.urbanladder.com/product/salford-sofa-cum-beds-in-moss-green-9292974'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Zehnloch 3 Seater Click Clack Sofa cum Bed In Glacier Blue Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$89$d$,
  $d$1$d$,
  $d$81$d$,
  $d$43.75 kg$d$,
  $d$Urban Ladder Home Decor Solutions Private Limited, Block C & D, Plot No. 1, 2nd Phase,Industrial Area, Sector - Bidadi,Bangalore-562109$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  14999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Im6zeiAJvG-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/4KHpeohxeb-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/zZb96XK_wR-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9Dwk5S9PMQ-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bcyLD6RMuY-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fX5K-Ray4-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/h81EIyM787-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/txuRTHpUvh-8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Im6zeiAJvG-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/4KHpeohxeb-2.png$d$,
  'https://www.urbanladder.com/product/zehnloch-3-seater-click-clack-sofa-cum-bed-in-glacier-blue-colour-7518895-8687476'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Kowloon Sectional 3 Seater Pull Out Sofa cum Bed In Daschund Brown Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$1$d$,
  $d$2$d$,
  $d$90$d$,
  $d$70.50 kg$d$,
  $d$A cozy spot for movie nights, and a guest room in disguise for unexpected overnight stays—this is the Kowloon Sofa-Cum-Bed, a sectional that masters the art of transformation. With a simple pull, the base glides open, unveiling a spacious double bed in seconds. The chaise lifts effortlessly, revealing a generous storage compartment to tuck away blankets, pillows, and everyday essentials. Thoughtfully placed side sleeves provide a dedicated home for magazines, newspapers, and more, keeping your living room as organised as it is inviting. Available in chenille fabric options, Kowloon’s plush, velvety texture is irresistibly soft to the touch. Designed to adapt to the rhythm of your life, the Kowloon Sectional Sofa does it all—with effortless style and comfort. - Available in three options: Daschund Brown, Baltic Blue in Premium Chenille Fabric and Urban Grey in Premium Chenille Fabric. - Indoor use only. - Please refer to the images for dimension details.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  49999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/IguucomcHw-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/IrrtIk8M8-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Pmg8hg9HUr-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Kc1vGA92I5-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/zY569YlUJX-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/GCvblBqQP6-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/1qm2eNVhzl-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/szU5WCgNmF-8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IguucomcHw-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/YCgOUqz8Urd-2.png$d$,
  'https://www.urbanladder.com/product/kowloon-sectional-3-seater-pull-out-sofa-cum-bed-in-daschund-brown-colour-7518884-8687463'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Camden Compact 3 Seater Pull Out Sofa cum Bed In Mocha Brown Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$2$d$,
  $d$1$d$,
  $d$69$d$,
  $d$88.75 kg$d$,
  $d$A gorgeous three-seater, the Camden compact sofa cum bed works not just as your primary seating option, but also as an elegant statement piece. It transforms easily from sofa to bed, in three simple steps. Easy to pull out, easy to put back. Make an instant guest room whenever you need! Or, simply enjoy your book or TV show in better comfort. Its armrests are steady and reliable - perfect for resting your elbow, book, or even the remote, when needed.$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  34999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/UQvdYiefZs-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/QQPEM-e25g-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/cbpghOJN23-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/A-H0KIQKvQ-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/hKrEz-SzK5-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/xf3G-ND877o-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/SPxmL8X5NSr-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/8MirK1oJpKL-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UQvdYiefZs-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/pNN0QVCA3H-2.jpg$d$,
  'https://www.urbanladder.com/product/camden-compact-3-seater-pull-out-sofa-cum-bed-in-mocha-brown-colour-7518898-8687479'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Peckham 3 Seater Click Clack Sofa Cum Bed In Oyster Beige Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$1$d$,
  $d$2$d$,
  $d$78$d$,
  $d$10.00 kg$d$,
  $d$Urban Ladder Home Decor Solutions Private Limited, Block C & D, Plot No. 1, 2nd Phase,Industrial Area, Sector - Bidadi,Bangalore-562109$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  54999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/cktGk0MJq6-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/E0O7-NiHWg-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/BZQCLYP5M7-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/kI6XxjCtS8-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Lxc6lkdIXZ-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YSSMCHx4SW-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/3MPRJRaQ7N-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/B023rRbyq-8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/cktGk0MJq6-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/T5Znp2m8h6-2.png$d$,
  'https://www.urbanladder.com/product/peckham-sofa-cum-bed-in-oyster-beige-9283851'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Palermo 3 Seater Click Clack Sofa cum Bed In Olive Green Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$1$d$,
  $d$1$d$,
  $d$40$d$,
  $d$65.35 kg$d$,
  $d$A fabric 3 seater sofa bed that transforms to a twin bed The internal click-clack mechanism allows an instant conversion from sofa to bed The plush cushions make it extremely soft and comfortable in either form Refer to the images for details of dimensions For indoor use only$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  24999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/84lSCC91_a-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/qSqbXqhxVN-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/mePdrWQY_K-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/L2E7R0Coh8-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Hb4A6-kWN-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/4uH395V5Px-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LJPHJ7UxkT-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Ee055BbIb8-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/84lSCC91_a-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/-OFidGz23p-2.jpg$d$,
  'https://www.urbanladder.com/product/palermo-3-seater-click-clack-sofa-cum-bed-in-olive-green-colour-7518904-8687505'),
($d$Collection / Sofa Cum Beds$d$,
  $d$Felicity 3 Seater Click Clack Sofa cum Bed In Midnight Indigo Blue Colour$d$,
  $d$Urban Ladder$d$,
  $d$Qty : 1$d$,
  12,
  $d$81$d$,
  $d$1$d$,
  $d$84$d$,
  $d$52.00 kg$d$,
  $d$Induces yawns. In a good way. Plush and comfy, the Felicity is every insomniac’s dream come true. A gentle push turns it into an inviting single bed. Perfect for small apartments and sudden guests. Choose from 3 delectable shades. It’ll sit pretty in your living room. Made of eucalyptus wood Foam cushioning Fabric upholstery The yellow and grey variants have a flat weave, while the cream variant has a plush, textured weave. The click-clack mechanism for ease of use Please refer to the images for dimension details$d$,
  NULL,
  $d$Fabric$d$,
  NULL,
  NULL,
  $d$3 Seater$d$,
  NULL,
  24999.00,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/qoeCS0pRhp-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/L0KSQDBUnV-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/p-s1DTBTgb-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/GaWc7ejKXZ-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/sbf6wS69_f-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5YLQcYHxr5-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/VyxVolPgAE-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/a9iO2oyTbR-8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qoeCS0pRhp-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/1XCNG2CXxf-2.png$d$,
  'https://www.urbanladder.com/product/felicity-3-seater-sofa-cum-bed-in-midnight-indigo-blue-colour-7518886-8687474');
