-- Cabinet / storage catalog (Urban Ladder). Own table: cabinet_products (not table_products).
-- DELETE + INSERT by product_url. Regenerate from 029 via repo script if needed.

DELETE FROM cabinet_products WHERE product_url = ANY(ARRAY[
  $d$https://www.urbanladder.com/product/rhodes-3-door-solid-wood-sideboard-in-amber-walnut-finish-7520279$d$,
  $d$https://www.urbanladder.com/product/baltoro-engineered-wood-sideboard-in-white-finish-7520328$d$,
  $d$https://www.urbanladder.com/product/dorian-engineered-wood-sideboard-with-ceramic-top-in-walnut-high-gloss-finish-9334267$d$,
  $d$https://www.urbanladder.com/product/striado-sideboard-finish-amber-walnut-metal-channel-8340924$d$,
  $d$https://www.urbanladder.com/product/nura-solid-wood-sideboard-in-danish-walnut-finish-9264864$d$,
  $d$https://www.urbanladder.com/product/carnegie-solid-wood-sideboard-in-amber-walnut-finish-8425981$d$,
  $d$https://www.urbanladder.com/product/vector-solid-wood-sideboard-in-amber-walnut-finish-9118755$d$,
  $d$https://www.urbanladder.com/product/tuscany-solid-wood-sideboard-in-latin-american-teak-finish-7520273-9420678$d$,
  $d$https://www.urbanladder.com/product/ramore-solid-wood-sideboard-in-mahogany-finish-9463972$d$,
  $d$https://www.urbanladder.com/product/morii-solidwood-chest-of-drawers-in-dual-tone-finish-9493266$d$,
  $d$https://www.urbanladder.com/product/elios-solidwood-sideboard-in-gold-ripple-and-black-brushed-finish-9654329$d$,
  $d$https://www.urbanladder.com/product/fleur-sideboard-8115708$d$,
  $d$https://www.urbanladder.com/product/bennis-25-pair-shoe-rack-in-dark-walnut-finish-7519250$d$,
  $d$https://www.urbanladder.com/product/webster-48-pair-shoe-rack-in-sheesham-finish-8701322$d$,
  $d$https://www.urbanladder.com/product/alex-21-pair-shoe-cabinet-in-classic-walnut-finish-9283675-9420837$d$,
  $d$https://www.urbanladder.com/product/alberto-bookshelf-display-unit-85-book-capacity-finish-teak-metal-channel-8375582$d$,
  $d$https://www.urbanladder.com/product/miles-engineered-wood-bookshelf-in-classic-walnut-finish-7518825-9420656$d$,
  $d$https://www.urbanladder.com/product/linnea-solid-wood-tv-cabinet-in-amber-walnut-finish-9333206$d$,
  $d$https://www.urbanladder.com/product/hayes-18-pair-shoe-rack-in-classic-walnut-finish-7519226-9420840$d$,
  $d$https://www.urbanladder.com/product/nina-12-pairs-solid-wood-shoe-cabinet-in-amber-walnut-finish-9774691$d$,
  $d$https://www.urbanladder.com/product/paxton-bookshelf-finish-amber-walnut-8340141$d$,
  $d$https://www.urbanladder.com/product/paleo-solid-wood-corner-bookshelf-in-danish-walnut-finish-9746369$d$,
  $d$https://www.urbanladder.com/product/vector-solid-wood-free-standing-tv-unit-in-mahogany-finish-7519415$d$,
  $d$https://www.urbanladder.com/product/torin-solid-wood-tv-cabinet-in-golden-ash-finish-9332706$d$,
  $d$https://www.urbanladder.com/product/malabar-bookshelf-display-cabinet-55-book-capacity-amber-walnut-metal-channel-8602675$d$,
  $d$https://www.urbanladder.com/product/takai-solid-wood-and-cane-bookshelf-table-in-red-cedar-finish-8861197$d$,
  $d$https://www.urbanladder.com/product/torin-solid-wood-bookshelf-in-danish-walnut-finish-9275532$d$,
  $d$https://www.urbanladder.com/product/tetris-solid-wood-bookshelf-in-walnut-finish-7518875$d$,
  $d$https://www.urbanladder.com/product/sydney-modular-medium-display-unit-in-beige-high-gloss-9390706$d$,
  $d$https://www.urbanladder.com/product/murano-bookshelf-cum-display-unit-finish-mango-walnut-8115710$d$,
  $d$https://www.urbanladder.com/product/amy-bookshelf-in-columbian-walnut-finish-9667544$d$,
  $d$https://www.urbanladder.com/product/paige-engineered-wood-bookshelf-in-frosty-white-finish-7518830$d$,
  $d$https://www.urbanladder.com/product/ohio-chest-of-drawer-in-amber-walnut-finish-8784930$d$,
  $d$https://www.urbanladder.com/product/toledo-solid-wood-chest-of-6-drawers-in-danish-walnut-finish-8340145$d$,
  $d$https://www.urbanladder.com/product/baltoro-engineering-wood-chest-of-5-drawers-in-white-finish-7520307$d$,
  $d$https://www.urbanladder.com/product/magellan-solid-wood-chest-of-6-drawers-in-teak-finish-9264861$d$,
  $d$https://www.urbanladder.com/product/bocado-tall-engineered-wood-chest-of-6-drawers-in-columbian-walnut-finish-7520312$d$,
  $d$https://www.urbanladder.com/product/ben-engineered-wood-chest-of-4-drawers-in-classic-walnut-finish-7520340-9420670$d$,
  $d$https://www.urbanladder.com/product/walter-chest-of-drawers-finish-amber-walnut-metal-channel-8701328$d$,
  $d$https://www.urbanladder.com/product/bennis-engineered-wood-chest-of-5-drawers-in-dark-walnut-finish-7520315$d$,
  $d$https://www.urbanladder.com/product/tuscany-solid-wood-chest-of-5-drawers-in-latin-american-teak-finish-7520311-9420676$d$,
  $d$https://www.urbanladder.com/product/masai-solid-wood-chest-of-drawers-in-american-walnut-2-tone-finish-8687935$d$,
  $d$https://www.urbanladder.com/product/alexandra-chest-of-drawer-finish-american-walnut-8280774$d$,
  $d$https://www.urbanladder.com/product/avelin-chest-of-drawer-finish-sage-green-with-burnt-mango-metal-channel-8425846-9420665$d$
]);

INSERT INTO cabinet_products (
  category, name, brand, colour, warranty_in_months, country_of_origin,
  length, width, height, net_weight, description,
  generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name,
  price, images_url, product_url
) VALUES
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Rhodes 3 Door Solid Wood Sideboard in Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$39$d$,
  $d$1$d$,
  $d$74$d$,
  $d$35.20 kg$d$,
  $d$Buy Rhodes 3 Door Solid Wood Sideboard in Amber Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  21999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qylk6TGIykX-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/k2sVa1kerI-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-kPW9utGO-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/A_AhwdnNZ2-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/yAMn6Xjui7-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/RBI6LJHUed-5.jpg$d$,
  $d$https://www.urbanladder.com/product/rhodes-3-door-solid-wood-sideboard-in-amber-walnut-finish-7520279$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Baltoro Engineered Wood Sideboard in White Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$44$d$,
  $d$1$d$,
  $d$80$d$,
  $d$21.00 kg$d$,
  $d$Buy Baltoro Engineered Wood Sideboard in White Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  29999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-qskbdKgxj-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/MWcuk5K3Lc-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/9iWdh5nIIN7-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XHQ71ncfBG1-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/daNhzeMwwrE-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/7ksbBADDY43-5.jpg$d$,
  $d$https://www.urbanladder.com/product/baltoro-engineered-wood-sideboard-in-white-finish-7520328$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Dorian Engineered Wood Sideboard With Ceramic Top In Walnut High Gloss Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$80$d$,
  $d$60.00 kg$d$,
  $d$Bold and sculptural, the Dorian side table anchors your living space with its exquisite design. The monolithic silhouette, softened by rounded edges, strikes a perfect balance between architectural precision and organic warmth. The marble-finish ceramic top with glossy painted surface enhances the clean, contemporary design. The plinth in a metal finish outlines the bottom, adding to the captivating silhouette. Discreet drawers with a push-to-open mechanism provide ample space for essentials—decor, books, or personal keepsakes. A versatile piece, Dorian transforms the everyday into moments of sophistication. - Elegantly veined marble-finish ceramic on top. - 2-drawer design. - A subtle plinth in a metal finish runs along the bottom. - Available in 2 options: 1. Walnut veneer with Marble Grey Ceramic top and gold-finish plinth. 2. Painted Cream high-gloss finish with Marble White Ceramic top and black-finish plinth.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  54999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/L0_D-1SY_S-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MbvJ77q_6-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/uvnRFviHst-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/KeF1prPhCj-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/3IfY8FbLlJ-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JKoPCTSbja-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nFLCVxwKyX-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/L0_D-1SY_S-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/nEri3IwlaM-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/MbvJ77q_6-b.jpg$d$,
  $d$https://www.urbanladder.com/product/dorian-engineered-wood-sideboard-with-ceramic-top-in-walnut-high-gloss-finish-9334267$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Striado Sideboard in Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$86$d$,
  $d$89.20 kg$d$,
  $d$Elegant design meets timeless craftsmanship in the Straido Sideboard. Defined by its rich finish options, it highlights the organic beauty of natural wood grain, telling a quiet story of time and artistry. The fluted top detail lends a sculptural quality, while smooth-glide drawers with accent metal knobs add a refined contrast of texture and form. Framed by a clean silhouette, the sideboard balances function with finesse. Shuttered storage doors open to reveal ample space, designed to hold heirloom dinnerware, treasured keepsakes, or everyday essentials. Whether positioned in a dining area, entryway, or as a statement piece in a living space, Straido brings warmth and sophistication to your home. Made from solid Mango wood. Available in two finish options: Amber Walnut and American Walnut. Please refer to images for dimension details. Indoor use only.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  32999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/b7HM6dGAGa-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/n6PydQ1JwB-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/1l9kAdx9VH-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/19A16aAhPu-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/i71eEUN0H2-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fCAS8sMw-o-g.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/5oBYsNhkU-f.png$d$,
  $d$https://www.urbanladder.com/product/striado-sideboard-finish-amber-walnut-metal-channel-8340924$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Nura Solid Wood Sideboard In Danish Walnut Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$40$d$,
  $d$1$d$,
  $d$80$d$,
  $d$70.28 kg$d$,
  $d$Inspired by Japanese minimalism, the Nura sideboard embodies a sense of calm order and functionality. Its handle-less doors and softly rounded corners create a seamless, sculptural form that blends effortlessly into modern interiors. Crafted from solid mango wood, the piece rests on bold cylindrical legs that provide both visual weight and balance. Behind its clean silhouette lies generous storage — ideal for dinnerware, serveware, or everyday essentials. The wide tabletop offers ample space to style décor accents, lamps, or art pieces, turning utility into sophistication. - Inspired by Japanese minimalist design. - Crafted from solid mango wood. - Available in 2 finish options: Danish Walnut and Black Wire Brush.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  47999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Gb6wbzTGz-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/v7EI1KsgR_-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Mj_-Tcvb3-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/7LDhwmDoCF-aa.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/tTQyyZPUrA-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-_2PR2z0Wo-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ElhT8HF_vp-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Gb6wbzTGz-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/fOXMasAkgC-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/v7EI1KsgR_-c.jpg$d$,
  $d$https://www.urbanladder.com/product/nura-solid-wood-sideboard-in-danish-walnut-finish-9264864$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Carnegie Display Cabinet in Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$1$d$,
  $d$80$d$,
  $d$35$d$,
  $d$44.30 kg$d$,
  $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  19999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/E04qTZtoAm-00Baseimage.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qXlQkx0eES-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/q3jqz68ZI-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/eIgJYBP9dT-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/29BTt_zt5U-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/mKNQsk1g_1-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/P7p78xCqsY-f.jpg$d$,
  $d$https://www.urbanladder.com/product/carnegie-solid-wood-sideboard-in-amber-walnut-finish-8425981$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Vector Solid Wood Sideboard in  Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$80$d$,
  $d$78.00 kg$d$,
  $d$Sambhav Timber & Handicrafts Pvt Ltd,E-216, Riico Industrial Area Phase - Iii,Boranada,Jodhpur-342012$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  27999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-lh82ZxZL6-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8f4c2N3_1c-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/p6IpxugHxv-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/whlm3H_e7-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/d77abA6hgr-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ca_Ak2VhVh-f.png$d$,
  $d$https://www.urbanladder.com/product/vector-solid-wood-sideboard-in-amber-walnut-finish-9118755$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Tuscany Solid Wood Sideboard in Latin American Teak Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$88$d$,
  $d$65.75 kg$d$,
  $d$The fancy hoarder. Inspired by the French country style the Tuscany Side board is made from pure teak wood. Soulfully luxurious, it features beautiful louvered panels and hand crafted moulded cornices that add a touch of whimsical. It safely stores all your things while looking absolutely gorgeous. Made of Teak Wood Please refer to images for dimension details Indoor use only For daily care, wipe with a soft, dry cloth$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  39999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/WMnPlo1eOc-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/P_w1K6Fhyb-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sXQm3emV4k-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/NoYVqpB2wE-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/byrOHFTyvc-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lTTsLmL2I_-5.jpg$d$,
  $d$https://www.urbanladder.com/product/tuscany-solid-wood-sideboard-in-latin-american-teak-finish-7520273-9420678$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Ramore Solid Wood Sideboard in Mahogany Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$38$d$,
  $d$1$d$,
  $d$82$d$,
  $d$45.50 kg$d$,
  $d$The Ramore Sideboard stands as both a statement and a storyteller. With its rich finish, it radiates a warmth that invites conversation, celebration, and the rituals of home. Designed to offer both display and discretion, its thoughtful combination of open shelving and closed storage makes space for fine crockery, cherished heirlooms, and everyday dining essentials. The classical turned legs speak to a heritage of craftsmanship, while its modern architectural silhouette ensures it feels at home in contemporary spaces. Smooth channel drawers and shutter doors, adorned with transitional knobs, open with ease, revealing a world of organised elegance within. - Made from solid Mango wood with a rich Amber Walnut finish.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  22999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lIdgq974S5-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ycfbYwuPW-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/WNc-Myj71g-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/OU-hMBV5Kz-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/OzBgU7zGnS-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/u7R9-dctKL-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XBT715ha3A-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jD2QEEMuoS-g.png$d$,
  $d$https://www.urbanladder.com/product/ramore-solid-wood-sideboard-in-mahogany-finish-9463972$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Morii Solidwood Sideboard in Dual Tone Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$95$d$,
  $d$76$d$,
  $d$41.00 kg$d$,
  $d$Morii solidwood storage in dual tone finish (Urban Ladder).$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  32999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MwS8o9UfP-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/xV0lfcoBb-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bvryRhBZJM-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Jd_PpuDO5P-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/f8s6Z7JQn-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/BlR8L2LGfO-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JvbxNtqm9j-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/MwS8o9UfP-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/MwS8o9UfP-a.jpg$d$,
  $d$https://www.urbanladder.com/product/morii-solidwood-chest-of-drawers-in-dual-tone-finish-9493266$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Elios Solid Wood Sideboard in Gold Ripple and Black Brushed Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$40$d$,
  $d$1$d$,
  $d$80$d$,
  $d$58.00 kg$d$,
  $d$Elios solidwood sideboard in gold ripple and black brushed finish (Urban Ladder).$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  49979,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/uFHoiUNwk-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/BTdg5Q4nW-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/qS8oueYt-w-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/XISnkTaKDP-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-eJu3uPEs-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/z8iB1ndja2-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Tez1wxsoZG-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/uFHoiUNwk-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/uFHoiUNwk-a.jpg$d$,
  $d$https://www.urbanladder.com/product/elios-solidwood-sideboard-in-gold-ripple-and-black-brushed-finish-9654329$d$
),
(
  $d$Collection / Cabinets And Sideboards$d$,
  $d$Fleur Solid Wood Sideboard in White & American Walnut finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$88$d$,
  $d$40$d$,
  $d$89$d$,
  $d$42.00 kg$d$,
  $d$Buy Fleur Sideboard & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  19999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/O3R3josV_-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/SvVnXMqkm-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/0hDm2mQCux-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JT_9V7WsaD-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/8pIu4-0x--e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/NSmf76U_j_-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ndx8kTa2zK-g.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/V8t4Fgod_1-h.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/O3R3josV_-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/O3R3josV_-a.jpg$d$,
  $d$https://www.urbanladder.com/product/fleur-sideboard-8115708$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Bennis 25 Pair Shoe Rack in Dark Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  NULL,
  NULL,
  $d$1$d$,
  $d$36$d$,
  $d$97$d$,
  $d$42.70 kg$d$,
  $d$Buy Bennis 25 Pair Shoe Rack in Dark Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  11499,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Zv-O7CSntx-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/9KZheGRp5k-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/eETfCzx-sp-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/9DavpoWqVu-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/igamwagwJ-Bennis-25-Pair-Shoe-Rack-in-Dark-Walnut-Finish.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/vTA2ftQruB-4.jpg$d$,
  $d$https://www.urbanladder.com/product/bennis-25-pair-shoe-rack-in-dark-walnut-finish-7519250$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Webster 48 Pair Shoe Rack in Sheesham Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$1$d$,
  $d$36$d$,
  $d$1$d$,
  $d$0.04 kg$d$,
  $d$Shoes tell stories of everyday adventures, spontaneous plans, and cherished moments. The Webster shoe cabinet ensures they have a perfect place to rest when the day is done. Featuring a warm finish and mid-century modern design, Webster is a must-have addition to your home. Behind its doors, multiple shelves keep your collection neatly tucked away, while soft-close hinges ensure every interaction feels effortless. A lockable cabinet adds a touch of security, and slender mid-century modern legs elevate the design with sophistication. More than a storage solution, Webster transforms everyday organisation into a statement of style. - Available in a variety of storage capacities. - Available in three finish options: Classic Walnut, Sheesham and Walnut. - Indoor use only. - Please refer to images for dimension details. NOTE: This shoe cabinet is designed to hold footwear of size 10 and below. For sizes above 10, please check out other shoe cabinets in our catalog$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  22999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fT8rHJ_sY0-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ecRQpXFdwp-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Tg_LJqSFDD-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/7WQM9OIzJM-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/X0hbAN8si-Webster-48-Pair-Shoe-Rack-in-Sheesham-Finish.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/InduTW0lsY-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DFlJ61hHrv-g.png$d$,
  $d$https://www.urbanladder.com/product/webster-48-pair-shoe-rack-in-sheesham-finish-8701322$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Alex 21 Pair Shoe Cabinet in Classic Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$35$d$,
  $d$1$d$,
  $d$99$d$,
  $d$19.00 kg$d$,
  $d$Your beautiful shoe collection deserves a quality shoe rack. Alex has been thoughtfully designed to store your footwear safely without taking up too much space. It has adjustable shelves which you can move at ease depending on your comfort. Keeping different shoes in mind, the bottom shelf is larger to accommodate bigger shoes. It comes in three different sizes so you can choose what best suits you. Modern and ergonomic, this is definitely the shoe rack you have been looking for. Made of engineered wood Easy assembly and dismantling Please refer to images for dimension details Indoor use only For daily care, wipe with a soft, dry cloth$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  6999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/475A7A0_5-Alex-21-Pair-Shoe-Cabinet-in-Classic-Walnut-Finish.jpeg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/FFw_rgem5-Alex-21-Pair-Shoe-Cabinet-in-Classic-Walnut-Finish.jpeg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/FNuKWX2lJ-Alex-21-Pair-Shoe-Cabinet-in-Classic-Walnut-Finish.jpeg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3cWvXaHoh-Alex-21-Pair-Shoe-Cabinet-in-Classic-Walnut-Finish.jpeg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/deMDlK-oN-Alex-21-Pair-Shoe-Cabinet-in-Classic-Walnut-Finish.jpeg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/KpTDOi666-Alex-21-Pair-Shoe-Cabinet-in-Classic-Walnut-Finish.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/WKWrZWeO3-Alex-21-Pair-Shoe-Cabinet-in-Classic-Walnut-Finish.jpeg$d$,
  $d$https://www.urbanladder.com/product/alex-21-pair-shoe-cabinet-in-classic-walnut-finish-9283675-9420837$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Alberto Solid Wood Bookshelf in Teak Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$30$d$,
  $d$92$d$,
  $d$1$d$,
  $d$74.55 kg$d$,
  $d$Part bookshelf, part raconteur—the Alberto Bookshelf does not just store books; it curates stories. Designed with a ladder-style silhouette, its asymmetrical shelving invites a sense of rhythm and spontaneity, offering the perfect stage for your treasured novels, kids storybooks, and objets dart. The dividers ensure that every piece finds its rightful place, without elbowing for space, while adding a quirky charm to your display. At the base, a discreet drawer keeps the tales you would rather not tell—be it stray papers, hidden keepsakes, or the odds and ends of everyday life. With its towering presence and slim footprint, Alberto maximizes vertical space, making it an elegant and practical addition to both large and compact interiors. The Alberto bookshelf with its modern design holds a world of possibilities. - Made of Sheesham wood. - Perfect bookshelf for showcasing your favourite books and décor pieces. - Available in two finishes: Teak and Mahogany. - Please refer to the images for dimension details. - Indoor use only.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  24999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/PQc-XAw0n-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IzJYP2KyKB-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/cyZltvGXuv-c.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/RB5zkLjXC--aa.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/waIvjvIXD--d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/U3b628F2g-e.png$d$,
  $d$https://www.urbanladder.com/product/alberto-bookshelf-display-unit-85-book-capacity-finish-teak-metal-channel-8375582$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Miles Engineered Wood Bookshelf In Classic Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$60$d$,
  $d$29$d$,
  $d$1$d$,
  $d$22.75 kg$d$,
  $d$The Miles Bookshelf is a piece of furniture that marries classic aesthetics with modern functionality. The rich walnut finish not only adds warmth and depth but also highlights the beautiful wood grain patterns. It complements various interior styles, from traditional to contemporary. Made from Engineered Wood Please refer to images for dimension details For indoor use only$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  3999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/O6oOXoI8rpy-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/QJT7YAP4awd-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/km7gSPmOHnc-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ENaKuvTyckk-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8KwEnJLc9S6-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZluthCd48pf-5.jpg$d$,
  $d$https://www.urbanladder.com/product/miles-engineered-wood-bookshelf-in-classic-walnut-finish-7518825-9420656$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Linnea Solid Wood TV Cabinet In Amber Walnut Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$41$d$,
  $d$32.00 kg$d$,
  $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071 Telephone No.: 080-69807777 Email ID: hello@urbanladder.com$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  19999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/v5RnF1Dicd-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/B-hBBusYjJ-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/de6tBlB2JN-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/t8wzjni3OJ-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/I3fYlqERI-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ouL7tjKp2K-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/OcqyI_uB8r-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/v5RnF1Dicd-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/B-hBBusYjJ-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/_dIQjGY3ek-b.jpg$d$,
  $d$https://www.urbanladder.com/product/linnea-solid-wood-tv-cabinet-in-amber-walnut-finish-9333206$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Hayes 18 Pair Shoe Rack In Classic Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  NULL,
  NULL,
  $d$61$d$,
  $d$35$d$,
  $d$1$d$,
  $d$32.65 kg$d$,
  $d$Urban Ladder Home Decor Solutions Private Limited, Block C & D, Plot No. 1, 2nd Phase,Industrial Area, Sector - Bidadi,Bangalore-562109$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  5999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2HhINqpuF3-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sWlP4Jl6Qv-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/choh_-hnO-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/mYdghS6nea-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/zzA6lUzGER-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XR1Hv50c1t-5.jpg$d$,
  $d$https://www.urbanladder.com/product/hayes-18-pair-shoe-rack-in-classic-walnut-finish-7519226-9420840$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Nina 12 Pairs Solid Wood Shoe Cabinet In Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  24,
  NULL,
  $d$42$d$,
  $d$46$d$,
  $d$1$d$,
  $d$35.00 kg$d$,
  $d$Make space for effortless storage. Designed with a rectangular form and clean edges, the Nina shoe cabinet lends contemporary elegance to your space. The defining visual element is the bold chevron pattern on the shutter, creating striking movement and depth across the surface. A slim metallic base in a brushed gold finish gently elevates the design, while the matching handle adds elegant contrast against the warm wood tones. Crafted from solid mango wood, Nina blends everyday functionality with thoughtful design, making it a seamless addition to foyers, hallways, and more. Available in two finishes: Amber Walnut and Mango Walnut. Offered in multiple configurations: 4-pair (with seating), 12-pair, and 24-pair storage, as well as combination units: 12+24, 12+4, 24+4, and 12+24+4 pairs. The seat is available in two finishes: Olive Leatherette and Taupe Leatherette. Made from solid mango wood for lasting durability.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  19999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UpGjAnvpky-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/37ZoDR1NJ_-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/F_poEpoYR6-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Vm0BBaknOp-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_QvOpkBovC-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Kl7Ca7ik3H-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/r8BylXY6Vr-f.png$d$,
  $d$https://www.urbanladder.com/product/nina-12-pairs-solid-wood-shoe-cabinet-in-amber-walnut-finish-9774691$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Paxton Bookshelf in Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  24,
  NULL,
  $d$19$d$,
  $d$40$d$,
  $d$1$d$,
  $d$17.00 kg$d$,
  $d$Revel in the quiet sophistication of our Paxton bookshelf. Its silhouette, a study in understated elegance, allows your curated collection to take center stage. Crafted from the rich tones of Mango wood, each shelf presents a robust platform, a testament to its enduring craftsmanship. The clean, unadorned lines are a deliberate choice, allowing the Paxton to seamlessly integrate into any milieu—from the formal dining room to the intimate hallway. Featuring several sturdy wooden shelves, there is room for everything you want to display. Paxton, with its versatile design, is a timeless choice for any home. Made from solid wood. Available in Amber Walnut and Danish Walnut finish options. Indoor use only. Please refer to the images for dimension details. For daily care, wipe with a soft, dry cloth.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  7999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/EdQRsrcBF2-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/mJejuPHu9-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/keiNDNA6AY-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3EYNjmAuCG-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/kf1eLnLjah-e.png$d$,
  $d$https://www.urbanladder.com/product/paxton-bookshelf-finish-amber-walnut-8340141$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Paleo Solid Wood Corner Bookshelf In Danish Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$53$d$,
  $d$25$d$,
  $d$1$d$,
  $d$22.45 kg$d$,
  $d$A home for your stories. With its angular partitions and asymmetrical dividers, the Paleo bookshelf introduces a touch of contemporary charm to your space. Designed with an open display concept, it keeps everything within easy reach while allowing your favourite pieces to stand out. The sleek vertical silhouette makes efficient use of height, offering generous room for books, décor accents, planters and collectibles. Crafted from solid wood in warm finish options, Paleo brings both durability and inviting warmth to living rooms, study corners, home offices and more. - Crafted from solid wood. - Available in two finish options: Amber Walnut and Danish Walnut. - 1 ft. shelf clearance for accessories of varying sizes. - Space-efficient 25 cm depth.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  14999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/83vnbVZin5-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/g3USR7y0k-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/KMQRSnQRtK-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/wD60nFi8z--cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/RWsA77VSjO-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/TZ7DkZ_Smj-f.png$d$,
  $d$https://www.urbanladder.com/product/paleo-solid-wood-corner-bookshelf-in-danish-walnut-finish-9746369$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Vector Solid Wood TV Unit in Mahogany Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$1$d$,
  $d$45$d$,
  $d$45$d$,
  $d$57.00 kg$d$,
  $d$Buy Vector Solid Wood Free Standing TV Unit in Mahogany Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  19999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/iMfeJYXDz2-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/B5MQixGjBV-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Q-A_lI3xdW-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/wu9JqKefvG-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/e92DbPZt1N-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/7DX8aj25j--5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IfDKRPI1HB-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/JLeerX3-Ha-7.jpg$d$,
  $d$https://www.urbanladder.com/product/vector-solid-wood-free-standing-tv-unit-in-mahogany-finish-7519415$d$
),
(
  $d$Collection / Living Storage$d$,
  $d$Torin Solid Wood TV Cabinet In Golden Ash Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$50$d$,
  $d$50.20 kg$d$,
  $d$With its contemporary silhouette and soft-edged detailing, the Torin TV cabinet brings elegance to modern living spaces. The gently curved profile creates a sense of visual harmony, while the warm mango wood lends the piece its unique character. Rich finishes catch the eye and define the room. Designed with a mix of open and closed storage, Torin offers ample space for your media units, books, and curated décor. - Available in two finish options: Golden Ash and Danish Walnut. - Crafted from solid Mango wood.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  29999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/lvxGXM4MLw-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/XOlVEaq3Gt-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FmlJunMrF6-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/wCraKcBvpS-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/KEWAW5v-vV-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Fk3skZ2fM-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/iBbecyd2mf-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lvxGXM4MLw-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/GSUSAzJAzM-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/XOlVEaq3Gt-b.jpg$d$,
  $d$https://www.urbanladder.com/product/torin-solid-wood-tv-cabinet-in-golden-ash-finish-9332706$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Malabar Bookshelf Display Cabinet 55 book Capacity Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$89$d$,
  $d$1$d$,
  $d$0.06 kg$d$,
  $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  34999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ubcOWmIvP-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/w-jbFdmdGc-aa.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/5MncAQ8CzP-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/N0BUdWruW6-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/i1IlffXxqy-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/n9RPQk1Pr-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/PquqU_Ow8r-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/57QeAfOa0S-h.png$d$,
  $d$https://www.urbanladder.com/product/malabar-bookshelf-display-cabinet-55-book-capacity-amber-walnut-metal-channel-8602675$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Takai Solid Wood and Cane Bookshelf In Red Cedar Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$40$d$,
  $d$87$d$,
  $d$1$d$,
  $d$49.00 kg$d$,
  $d$A home for your stories and keepsakes, the Takai bookshelf turns storage into art. The sculptural ball feet immediately draw attention, giving the piece a signature presence. Crafted from solid mango wood in a warm red cedar finish, it balances natural warmth with a whiff of nostalgia. Soft, rounded edges lend a gentle grace to the contemporary silhouette. Designed with both open shelves and closed cabinets, it offers versatile storage for everything—from your book collections and decor pieces to cherished keepsakes. Embodying the modern Japandi style, the bookshelf is accentuated with cylindrical accents in brass finish, making it as timeless as it is distinctive. - Crafted from mango wood in red cedar finish. - Natural woven cane shutters with cylindrical brass finish accents. - A signature piece from the Takai range, defined by the sculptural ball feet design and woven cane accents.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  33999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MSdalGagLX-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LgdqiFHpZk-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/6qJvnsHJn8-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nML71tjpxk-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/VOmMm0VgK--e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/kpC3TghBu-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/MSdalGagLX-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/MSdalGagLX-a.jpg$d$,
  $d$https://www.urbanladder.com/product/takai-solid-wood-and-cane-bookshelf-table-in-red-cedar-finish-8861197$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Torin Solid Wood Bookshelf In Danish Walnut Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$38$d$,
  $d$98$d$,
  $d$1$d$,
  $d$63.45 kg$d$,
  $d$The Torin bookshelf with its signature curves and soft-edged detailing brings a sense of harmony to your space. Crafted from mango wood, its warm tone and rich finish lend a tactile charm that creates a perfect backdrop for your favourite books, and décor pieces. Mix of open and closed storage offer generous space while maintaining an airy, elegant presence. With its contemporary sillhoute and sculptural grace, Torin elevates your cherished nook. - Available in two finish options: Golden Ash and Danish Walnut. - Crafted from solid Mango wood.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  35999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ub7-50aPL-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Gq2P7u24p-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/d9V5Coc30u-c.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/o7BKc6mcFs-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/owcKjpTXIX-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/si69rHEu8I-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FNI-9Dd9-x-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ub7-50aPL-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Gq2P7u24p-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/2toL8yERW-b.jpg$d$,
  $d$https://www.urbanladder.com/product/torin-solid-wood-bookshelf-in-danish-walnut-finish-9275532$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Tetris Solid Wood Bookshelf in Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$85$d$,
  $d$30$d$,
  $d$59$d$,
  $d$15.90 kg$d$,
  $d$Buy Tetris Solid Wood Bookshelf in Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  6999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/RApXsMEPez-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UFHPS-HVvN-b.jpg$d$,
  $d$https://www.urbanladder.com/product/tetris-solid-wood-bookshelf-in-walnut-finish-7518875$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Sydney Modular Medium Display Unit in Beige High Gloss$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$39$d$,
  $d$50$d$,
  $d$1$d$,
  $d$35.00 kg$d$,
  $d$Inspired by the modern charm of Sydney, this display unit brings the city’s effortless sophistication to your living space. Its clean-lined silhouette blends glossy and wood-grain finishes, creating a balanced aesthetic. The open shelves invite you to curate — from books and ceramics to treasured keepsakes — while the concealed compartments ensure everyday essentials stay neatly tucked away. Perfect for living rooms or dining spaces, it brings thoughtful design and effortless elegance together in one versatile piece. - Glossy finish. - Part of the Sydney range.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  13799,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Os-bSyouyc-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TH-MCvDDkk-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-ahFQlt8tJ-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/6_KvsY0u_T-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/OIDvMWEzn-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/326YlGWVUB-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/KLTmQk9zuP-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Os-bSyouyc-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/Os-bSyouyc-a.jpg$d$,
  $d$https://www.urbanladder.com/product/sydney-modular-medium-display-unit-in-beige-high-gloss-9390706$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Murano Bookshelf cum Display Unit Finish Mango Walnut - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$60$d$,
  $d$40$d$,
  $d$1$d$,
  $d$55.00 kg$d$,
  $d$Buy Murano Bookshelf cum Display Unit Finish - Mango Walnut & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  27999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UwwMiD1hQ-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Izsbt73yOI-02.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UmirsfAOHT-03.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ghvrZNdOR-04.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DsTynFbAfc-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/JISPKo34K6-06.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/pP8_MEdwaW-08.png$d$,
  $d$https://www.urbanladder.com/product/murano-bookshelf-cum-display-unit-finish-mango-walnut-8115710$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Amy Bookshelf in Columbian Walnut Finish - Gudsmith$d$,
  $d$Gudsmith$d$,
  NULL,
  48,
  NULL,
  $d$27$d$,
  $d$30$d$,
  $d$88$d$,
  $d$10.00 kg$d$,
  $d$Gudsmith: #1/3 , Sollarpuradamma Layout Heganahalli Main Road, Off, Magadi Main Rd, Sunkadakatte, Bengaluru, Karnataka 560091$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  1826,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/AjJhpWUIV-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/izQBvgz85e-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/s_TyhRvl40-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/VcxkzI7vZO-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/gnlzo7Wd9_-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/129YyFc5lr-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/FQg0gICGOf-7.jpg$d$,
  $d$https://www.urbanladder.com/product/amy-bookshelf-in-columbian-walnut-finish-9667544$d$
),
(
  $d$Collection / Bookshelf$d$,
  $d$Paige Tall Storage Cabinet in Frosty White - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$40$d$,
  $d$80$d$,
  $d$1$d$,
  $d$39.20 kg$d$,
  $d$Buy Paige Tall stoarge cabinet - Frosty White & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  14999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/dLr58mk4nL-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/20S_mldprM-02.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/CyUFitpIeH-03.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/cBOOGdDfcu-04.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/rHvgcQ7i2I-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nhN2SlQNzC-06.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/NXa91PTO9Z-08.png$d$,
  $d$https://www.urbanladder.com/product/paige-engineered-wood-bookshelf-in-frosty-white-finish-7518830$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Ohio Chest of Drawer in Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$85$d$,
  $d$73.25 kg$d$,
  $d$Because there’s always hope you’ll fit into those old jeans one day. Six roomy drawers make sure you never have to throw anything out again. There’s also an open shelf for easy access to keys and toiletries. Prop a mirror on top, and you now also have a dresser. Need we say more? Made from sheesham wood Back panel and drawer base made of MDF Available in 2 finishes Please refer to images for dimension details For indoor use only$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  27999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/LfkpIGEodB-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/yjW1HorYXu-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/21t3ujFNRH-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/T1WlT5HNs-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Iz6nRc8oNb-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2Iwya6LV3F-g.jpg$d$,
  $d$https://www.urbanladder.com/product/ohio-chest-of-drawer-in-amber-walnut-finish-8784930$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Toledo Solid Wood Chest of 6 Drawers In Danish Walnut Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$85$d$,
  $d$5.55 kg$d$,
  $d$A masterpiece of design and purpose, Toledo Chest of Drawers ensures elegance is effortless, and functionality feels indulgent. Featuring a rich Danish walnut finish, this piece is crafted to infuse an organic charm into every moment. The C-flute pattern creates a visual rhythm, drawing the eye to its sculptural beauty. Each of the six drawers glides open with a discreet push mechanism, revealing a world of organised serenity—accented by matte gold-finished handles that whisper elegance. Soft rounded fillet elements lend a gentle, tactile elegance, making every interaction a delight. Every detail in the Toledo Chest of Drawers is a testament to graceful craftsmanship. - This chest of drawers is part of our Toledo bedroom range, featuring unique C-flute patterns and round fillet edges. - Designed for a timeless contemporary appeal.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  29999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/FoKMq6qkfC-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Wp5Kh0AoW-c.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/upIF_s-0eN-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/aRa8dO1jH3-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/OAHaTxzB3i-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9pVaFr_ver-h.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/FoKMq6qkfC-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/HquLW4tkd8-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Wp5Kh0AoW-c.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/FoKMq6qkfC-a.jpg$d$,
  $d$https://www.urbanladder.com/product/toledo-solid-wood-chest-of-6-drawers-in-danish-walnut-finish-8340145$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Baltoro Engineered Wood Chest of 5 Drawers in White Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$1$d$,
  $d$44$d$,
  $d$93$d$,
  $d$23.60 kg$d$,
  $d$Buy Baltoro Engineering Wood Chest of 5 Drawers in White Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  28999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/1gnuXhRZ9LI-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ggahHNxNWP7-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fVy-ERtKS0W-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jI7_niFDs1z-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/idmfuyPDRLG-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jPR2Q3Tl-7x-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UF5VFIeISLf-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jN7egQEakUe-8.jpg$d$,
  $d$https://www.urbanladder.com/product/baltoro-engineering-wood-chest-of-5-drawers-in-white-finish-7520307$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Magellan Solid Wood Chest of 6 Drawers in Teak Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$45$d$,
  $d$1$d$,
  $d$88$d$,
  $d$70.00 kg$d$,
  $d$For all your everyday essentials, the Magellan chest of drawers is a space-saving solution with timeless appeal. Crafted from solid Sheesham wood, its clean-lined silhouette lends character and depth to your space. The rich finish defines the room with organic warmth. Multiple drawers offer generous storage for clothes, linens, grooming essentials, and more. Designed for order and elegance, Magellan brings seamless organisation to everyday living. - Made from solid Sheesham wood. - Available in Teak and Mahogany finish options.$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  26999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/BIRn--Cyi-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/PPb02dp2hV-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_B946DXod6-aa.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/xI30EMo7Rm-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jugviV1npV-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-Uf1Q_XGwZ-e.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jVDVhtev6-f.png$d$,
  $d$https://www.urbanladder.com/product/magellan-solid-wood-chest-of-6-drawers-in-teak-finish-9264861$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Bocado Tall Engineered Wood Chest of 6 Drawers in Columbian Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$39$d$,
  $d$69$d$,
  $d$1$d$,
  $d$5.20 kg$d$,
  $d$Buy Bocado Tall Engineered Wood Chest of 6 Drawers in Columbian Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  14999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/p_N37BWaMJ-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/AnUgrIbhDH-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/cOXYTJ2tOK-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Kdf2mvrynY-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZIE2Nrw2qn-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Z-jTbkzrQB-5.jpg$d$,
  $d$https://www.urbanladder.com/product/bocado-tall-engineered-wood-chest-of-6-drawers-in-columbian-walnut-finish-7520312$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Ben Engineered Wood Chest of 4 Drawers in Classic Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$53$d$,
  $d$40$d$,
  $d$81$d$,
  $d$32.10 kg$d$,
  $d$A visual delight. Our contemporary Ben chest of drawers comes with four spacious drawers that slide open smoothly. Prop a mirror above to double it up as a tiny dresser or place some plants or photos for a touch of colour. A wonderfully versatile piece, this can be repurposed endless times to fit in any corner of your home. Made from Engineered Wood For indoor use only Please refer to images for dimension details$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  6499,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/AMkzHADHS2-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/4-lggAsLAn-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3ZRaxTgj0y-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/eHMXt7uaiY-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jdjA-GzSYb-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/u2i3fHjMO0-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/19IfN5Y7SE-6.jpg$d$,
  $d$https://www.urbanladder.com/product/ben-engineered-wood-chest-of-4-drawers-in-classic-walnut-finish-7520340-9420670$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Walter Solid Wood Chest of Drawers in Amber Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$40$d$,
  $d$70$d$,
  $d$87$d$,
  $d$35.90 kg$d$,
  $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  16999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jSyDVZ_RX-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/F4ZdDM9D-t-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/NT4dabtm-a-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/LmuhSn_Qy2-d.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/eqauIPfFT-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/5bRFlfdtR-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lqbt-MUgLs-g.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qAqFuKqxF3-h.png$d$,
  $d$https://www.urbanladder.com/product/walter-chest-of-drawers-finish-amber-walnut-metal-channel-8701328$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Bennis Engineered Wood Chest of 5 Drawers in Dark Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  12,
  NULL,
  $d$59$d$,
  $d$39$d$,
  $d$1$d$,
  $d$45.75 kg$d$,
  $d$Buy Bennis Engineered Wood Chest of 5 Drawers in Dark Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$,
  NULL,
  $d$Engineered Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  11999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/JygNfMRZ6-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/hP6E_cgoKb-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2dSwk-e6Cc-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/TaQhhZcnfO-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/59eSNx0tho-4.jpg$d$,
  $d$https://www.urbanladder.com/product/bennis-engineered-wood-chest-of-5-drawers-in-dark-walnut-finish-7520315$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Tuscany Solid Wood Chest of 5 Drawers in Natural Teak Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$44$d$,
  $d$1$d$,
  $d$88$d$,
  $d$52.60 kg$d$,
  $d$Keeper of gorgeousness. Inspired by the French country style, the Tuscany Chest of Drawers is made from pure latin american teak wood. Soulfully luxurious, it features beautiful louvered panels and hand crafted moulded cornices that add a touch of whimsical. It safely stores all your things while looking absolutely gorgeous. Bring this home for a touch of French. Made of Teak Wood. Please refer to images for dimension details Indoor use only For daily care, wipe with a soft, dry cloth$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  28999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/S05VtzSEwD-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/SbD3LPAHzq-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/4qURGrLpeV-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/zZp_lpUcNl-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/90CJKZPvUP-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/IUSlWHw1c9-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZFghyjkeww-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/93QSBEZ_Bw-7.jpg$d$,
  $d$https://www.urbanladder.com/product/tuscany-solid-wood-chest-of-5-drawers-in-latin-american-teak-finish-7520311-9420676$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Masai Solid Wood Chest Of Drawers In American Walnut Finish With 2 Tone Finish$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$47$d$,
  $d$90$d$,
  $d$90$d$,
  $d$44.00 kg$d$,
  $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  24999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/vIAhh9_CPe-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TsmSY5RnEh-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/L78AkcMtlL-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/OFgIgSnmgG-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ehSDUIJcD5-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/pM-GOvpvHe-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/vIAhh9_CPe-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/vIAhh9_CPe-a.jpg$d$,
  $d$https://www.urbanladder.com/product/masai-solid-wood-chest-of-drawers-in-american-walnut-2-tone-finish-8687935$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Alexandra Chest of Drawers in American Walnut Finish - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$55$d$,
  $d$44$d$,
  $d$1$d$,
  $d$44.90 kg$d$,
  $d$Elevate your bedroom or any living space with the Alexandra Chest of 5 Drawers, a masterpiece of furniture that effortlessly marries timeless elegance with practical functionality. Handcrafted with meticulous attention to detail, this chest of drawers is a testament to the enduring beauty of solid wood craftsmanship. Please refer to images for dimension details For indoor use only$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  19999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8EpkRZfD3J-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/GtXauippAh-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/F3I16LwwMQ-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fG1d0w5ssr-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/NFdTlwJVEG-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/m2SAdg9f2p-6.png$d$,
  $d$https://www.urbanladder.com/product/alexandra-chest-of-drawer-finish-american-walnut-8280774$d$
),
(
  $d$Collection / Chest Of Drawers$d$,
  $d$Avelin Chest of Drawer-Finish- Sage green with Burnt mango - Metal Channel - Urban Ladder$d$,
  $d$Urban Ladder$d$,
  NULL,
  36,
  NULL,
  $d$70$d$,
  $d$37$d$,
  $d$87$d$,
  $d$32.30 kg$d$,
  $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$,
  NULL,
  $d$Solid Wood$d$,
  NULL,
  NULL,
  NULL,
  NULL,
  15999,
  $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/mPt4AH_4A-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/a2JXOilDe0-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/usjQgSKhqt-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/W_7pyo0Te-Avelin-Chest-of-Drawer-Finish-Sage-green-with-Burnt-mango-Metal-Channel.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/t-gz5XJZwO-e.jpg$d$,
  $d$https://www.urbanladder.com/product/avelin-chest-of-drawer-finish-sage-green-with-burnt-mango-metal-channel-8425846-9420665$d$
);
