-- Dedicated dining table catalog (separate from table_products)
CREATE TABLE IF NOT EXISTS dining_table_products (
  id bigserial PRIMARY KEY,
  category text,
  name text NOT NULL,
  brand text,
  colour text,
  warranty_in_months int,
  country_of_origin text,
  length text,
  width text,
  height text,
  net_weight text,
  description text,
  generic_name text,
  primary_material_type text,
  primary_material_subtype text,
  primary_room text,
  seating_capacity text,
  product_model_name text,
  price numeric(12,2),
  images_url text,
  product_url text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dining_table_products_brand ON dining_table_products(brand);
CREATE INDEX IF NOT EXISTS idx_dining_table_products_category ON dining_table_products(category);

ALTER TABLE dining_table_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read dining_table_products" ON dining_table_products;
CREATE POLICY "Allow public read dining_table_products"
  ON dining_table_products
  FOR SELECT
  USING (true);

INSERT INTO dining_table_products (
  category, name, brand, colour, warranty_in_months, country_of_origin,
  length, width, height, net_weight, description,
  generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name,
  price, images_url, product_url
) VALUES
($d$Collection / Dining Table Set$d$, $d$Caribu 4 To 6 Extendable - Ingrid (Fabric) 6 Seater Dining Table Set (Colour- Dark Grey) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$Dark Grey$d$, 12, NULL, $d$1$d$, $d$79$d$, $d$75$d$, $d$26.50 kg$d$, $d$Yiman Shuangxin Furniture Co.,Ltd.,North Of Jinbao Road, Tangerli Town, Bazhou City, Hebei Province, China-65702$d$, NULL, $d$Metal$d$, NULL, NULL, NULL, NULL, 71996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/pfVSzGmd3HA-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3bN8waD1rCS-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_S0YVbc9kVW-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8IyAIkJUMHL-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ctM58S-zd19-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/RDpNnLKd8Q9-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/04yY6CXaAjR-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/A4kJ1umJl-V-8.jpg$d$, $d$https://www.urbanladder.com/product/caribu-4-to-6-extendable-ingrid-fabric-6-seater-dining-table-set-colour-dark-grey-9777508$d$),
($d$Collection / Dining Table Set$d$, $d$Augusta 6 Seater Dining Set (Chair Colour- Grey, Finish- Dark Walnut)$d$, $d$ByUrban Ladder$d$, $d$Crush Sale â Up to 70% OFF! Shop Now$d$, 12, NULL, $d$90$d$, $d$1$d$, $d$74$d$, $d$27.00 kg$d$, $d$FNCOMB62GY32058$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 30996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-N_sP9cjHm-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Jnt0N5uxb_-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Jf1XIly6xz-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/d6eiKdej58-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TcX7_vKToK-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/VajXjY2QU1-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/3UctTr4-T7-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_J--4PArCt-8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-N_sP9cjHm-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/-N_sP9cjHm-1.jpg$d$, $d$https://www.urbanladder.com/product/augusta-6-seater-dining-set-colour-grey-finish-dark-walnut-8729615$d$),
($d$Collection / Dining Table Set$d$, $d$Vanalen 6-To-8 Extendable Glass Top Dining Table With 6 Dalla Chairs(Chair Colour- Grey , Finish- Dark Walnut) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$Crush Sale â Up to 70% OFF! Shop Now$d$, 12, NULL, $d$2$d$, $d$89$d$, $d$74$d$, $d$40.00 kg$d$, $d$FNDNDWGYC042032$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 51996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/g56Tlvxz81-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8_lUsFI3gk-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/38UhNsBN0w-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/v8y1Rkuw-j-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/HiuRmO918o-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Vq_u_FE8wr-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/T96GWAgipE_-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UZpv6Di8iBg-8.png$d$, $d$https://www.urbanladder.com/product/vanalen-6-to-8-extendable-dalla-6-seater-glass-top-dining-table-set-8729588$d$),
($d$Collection / Dining Table Set$d$, $d$Paloma 6 Seater Jupiter Spanish Ceramic Dining Table With 6  Beck Dining Chairs (Finish : Jupiter Spanish Ceramic, Chair Colour : Olive Leatherette) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$: Olive Leatherette)$d$, 24, NULL, $d$1$d$, $d$2$d$, $d$76$d$, $d$130.00 kg$d$, $d$Brings together warmth and comfort with PalomaÂBeck dining set. The dining table anchors the space with its Spanish ceramic top and sculptural base, creating a welcoming centre for both everyday meals and spirited gatherings. Its generous layout encourages shared moments, from slow breakfasts to lively dinners. Paired with the Beck dining chairs, the set leans into relaxed sophistication. The lounge-inspired form, contoured detailing, and high-back support make it easy to stay seated longer, while the swivel base allows for effortless movement around the table. Together, Paloma and Beck create a dining space that feels considered, comfortable, and easy to live with. Available in 6 and 8 seater options.$d$, NULL, $d$Metal$d$, NULL, NULL, NULL, NULL, 179996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/dXEUCDd0xb-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/7hGMAktYwV-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XFP4Fa_RH2-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/lrqGMc0J7f-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/RaBZo8kUbq-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/wGd3_Yvvsy-f.gif | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/jjobthLwF-g.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Upei9s4Kac-h.png$d$, $d$https://www.urbanladder.com/product/paloma-6-seater-jupiter-spanish-ceramic-dining-table-with-beck-dining-chairs-9507684$d$),
($d$Collection / Dining Table Set$d$, $d$Emry Rectangular Statuario Ceramic 6 Seater Dining Table With 6  Clarke Dining Chairs (Finish : Danish Walnut, Chair Colour : Tan Leatherette) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$: Tan Leatherette)$d$, 12, NULL, $d$90$d$, $d$1$d$, $d$76$d$, $d$47.05 kg$d$, $d$Designed for homes that celebrate everyday elegance, the Emry-Clarke dining set blends sculptural form with natural warmth.Â  The Emry table anchors the space with sophistication, its smooth ceramic top, framed by a floating edge, rests gracefully on a solid mango wood base. Elegant veining traces across the surface, catching light and conversation alike.  Surrounding it, the Clarke chairs bring a charm to the ensemble. Their gently contoured backrests and cushioned seats invite long, unhurried meals, while the solid wood frame lends timeless strength and texture. Subtle curves and tapered legs give the silhouette a poised lightness.  Together, they create a dining experience defined by harmony, of materials, craftsmanship, and the simple pleasure of gathering around good design.  Available in 4 and 6 seater options.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 70496.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/wuGaMfcPV-0.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/l4MPkjqfiV-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/AV2vdq8J6o-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/aWBoRciZc0-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DMq6s6wGRG-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/BpPYfjq9Yy-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Dm7UkR_lj_-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/0HPrDzxAtF-9.jpg$d$, $d$https://www.urbanladder.com/product/emry-rectangular-statuario-ceramic-6-seater-dining-table-with-clarke-dining-chair-9309315$d$),
($d$Collection / Dining Table Set$d$, $d$Lawson 6 Seater Dining Table Set (Chair Colour- Dark Brown, Finish- Walnut) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$Dark Brown$d$, 12, NULL, $d$1$d$, $d$89$d$, $d$74$d$, $d$27.80 kg$d$, $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 32996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/7ikPCuNVwYO-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/iJbd2AFgUUO-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/492PnaJLXPC-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/4OdQdKyFQ4X-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/xRjPTMspt1o-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZoeBdh_vlbF-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/_68WbgITm-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/nztQFn3XN--8.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/AN7EunPnF2-9.jpg$d$, $d$https://www.urbanladder.com/product/lawson-6-seater-dining-table-set-chair-colour-dark-brown-finish-walnut-9777514$d$),
($d$Collection / Dining Table Set$d$, $d$Atlas Solid Wood 6 Seater Dining Table With 6 Atlas Dining Chairs (Finish : Danish Walnut, Chair Colour : Avocado Green) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$: Avocado Green)$d$, 36, NULL, $d$89$d$, $d$1$d$, $d$74$d$, $d$47.30 kg$d$, $d$Atlas Solid Wood 6 Seater Dining Table With 6 Atlas Dining Chairs (Finish : Danish Walnut, Chair Colour : Avocado Green)$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 48996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/n5CiUOT_gQ-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/WfecVxrMh7-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/mIOCg428va-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ZMiTDMFeHW-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/O8SpbbEFv4-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/UTq0VUKeXB-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Sxr9Z9pLP3-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/tpPeGi9_26r-8.jpg$d$, $d$https://www.urbanladder.com/product/atlas-solid-wood-6-seater-dining-table-with-atlas-dining-chair-set-9685983$d$),
($d$Collection / Dining Table Set$d$, $d$Dune Solid Oak Wood Dining Table With 6 Dune Solid Wood Dining Chairs (Finish : Gradient Oak, Chair Colour : Deep Olive Velvet) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$: Deep Olive Velvet)$d$, 12, NULL, $d$90$d$, $d$1$d$, $d$72$d$, $d$86.00 kg$d$, $d$Inspired by the natural poetry of desert landscapes, the Dune dining set brings together fluid form and organic materiality. The Dune dining table captures the soft gradation of dusk across its rounded oak wood top, where natural texture and gentle curves create a sense of calm movement. Palm treeÃâinspired legs add sculptural character, grounding the design while keeping it light and expressive. Paired with the Dune dining chairs, the setting feels cohesive and inviting. The chairscurved silhouette and plush upholstery introduce softness, while the warmth of wood adds depth and tactility. Together, the Dune table and chairs create a dining space that feels ethereal, welcoming, and made to linger around. Available in a 6-seater option.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 118993.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/XnLdpxMdM-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/tq1hM1W3r-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/u46HgMcO4-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sP6XggIph0-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/bsiLh7jO3H-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/OUlVjAuF16-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/KGf62HVvYy-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/s1QOLhAfgz-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/YVldqT7kuv-9.png$d$, $d$https://www.urbanladder.com/product/dune-solid-oak-wood-dining-table-with-6-dune-solid-wood-dining-chairs-finish-gradient-oak-chair-colour-deep-olive-velvet-9777479$d$),
($d$Collection / Dining Table Set$d$, $d$Lawson 4 Seater Dining Table Set (Chair Colour- Dark Brown, Finish- Walnut) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$Crush Sale â Up to 70% OFF! Shop Now$d$, 12, NULL, $d$1$d$, $d$74$d$, $d$74$d$, $d$18.50 kg$d$, $d$Reliance Retail Limited, 1st, 2nd & 3rd Floor, No. 259 and 276 Amarjyothi, Basaveshwara HBCS Layout, Domlur, Bengaluru, 560071, Telephone No.: 080-69807777, Email ID: hello@urbanladder.com$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 21997.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/YDVKUAcQYzj-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/32pFj4BVJ27-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Tqj-TQqbfcz-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/aII3yvqdZDq-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/U2AehD43kya-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/3P2jMsZ_qvS-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/GQMQ7W5X4QL-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/LJJAcr4JhOz-8.jpg$d$, $d$https://www.urbanladder.com/product/lawson-4-seater-dining-table-set-colour-dark-brown-finish-walnut-8729655$d$),
($d$Collection / Dining Table Set$d$, $d$Aeris 6 To 8 Seater Extendable Dining With 6 Casey  Chairs (Finish : Gilded White, Chair Colour : Olive & Tan Colour) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$: Olive & Tan Colour)$d$, 12, NULL, $d$90$d$, $d$2$d$, $d$76$d$, $d$157.00 kg$d$, $d$Modern yet timeless, the Aeris-Casey set celebrates sculptural elegance and effortless comfort.  At its heart, the Aeris dining table stands as a statement of fluid form and balance. Its stone-inspired ceramic top lends a tactile richness, while the butterfly-shaped brass base adds poise and structure. With an extendable design, it transitions easily from intimate dinners to festive gatherings.  Paired with the Casey dining chairs, the set invites both ease and sophistication. The chairâs plush upholstery introduces a contemporary edge, while its 360-degree swivel and plush padding ensure every conversation flows with comfort and grace.  Together, they transform your dining space into one that feels warm, welcoming, and artfully designed for connection.  Comfortably seats 6, extends to accommodate up to 8 guests.$d$, NULL, $d$Metal$d$, NULL, NULL, NULL, NULL, 139996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/qgPUsONZl0-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/cJCQeMr_zu-cc.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2ik9f9bCVd-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/NQmouzbm00-c.gif | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2GrWetCY1-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/fGOI0qbxNr-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/usijh1HvG5-f.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-gueakKfGu-h.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/xNG_NN7ccL-j.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/sFM0N7ZIVg-k.jpg$d$, $d$https://www.urbanladder.com/product/aeris-ceramic-6-to-8-seater-extendable-dining-table-with-casey-dining-chair-9358792$d$),
($d$Collection / Dining Table Set$d$, $d$Diner 6 Seater Dining Table With 6 Dining Chairs (Finish : Golden Oak, Chair Colour : Oak)$d$, $d$ByUrban Ladder$d$, $d$: Oak)$d$, 12, NULL, $d$89$d$, $d$1$d$, $d$76$d$, $d$44.50 kg$d$, $d$FNDNGOGOC095059$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 41996.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5rDfaj2FvC-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/8fTuj-X1nv-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/IwmJDZSDbd-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bEy0Vzcj7j-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/AORUvDcdQ5-5.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5HeWh6hI8w-6.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YK0khbu-NP-7.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/NE_AZwnKjH-8.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/5rDfaj2FvC-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/5rDfaj2FvC-1.jpg$d$, $d$https://www.urbanladder.com/product/diner-6-seater-dining-table-set-finish-golden-oak-8729608$d$),
($d$Collection / Dining Table Set$d$, $d$Arabia 6 Seater Dining Table With 6 Kerry Chairs (Chair Colour- Burnt Orange , Finish- Teak) - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$Burnt Orange$d$, 36, NULL, $d$1$d$, $d$90$d$, $d$77$d$, $d$52.60 kg$d$, $d$Sambhav Timber & Handicrafts Pvt Ltd G - 749/750, Industrial Area, Phase IV, RIICO, Boranada, Jodhpur, Rajasthan 342012$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 44496.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/AHPOfP2ASd5-1.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/HWneITIlFbg-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/uOkuhKNnVZz-3.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/HPiolQksM3h-4.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2G5UZcZn-3w-5.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/DSFBf5jaB-6.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/5o76nOkVrF-7.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8rb-W_htKJ-8.png$d$, $d$https://www.urbanladder.com/product/arabia-kerry-6-seater-dining-table-set-teak-finish-burnt-orange-8240571$d$);

CREATE TABLE IF NOT EXISTS dining_chair_products (
  id bigserial PRIMARY KEY,
  category text,
  name text NOT NULL,
  brand text,
  colour text,
  warranty_in_months int,
  country_of_origin text,
  length text,
  width text,
  height text,
  net_weight text,
  description text,
  generic_name text,
  primary_material_type text,
  primary_material_subtype text,
  primary_room text,
  seating_capacity text,
  product_model_name text,
  price numeric(12,2),
  images_url text,
  product_url text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dining_chair_products_brand ON dining_chair_products(brand);
CREATE INDEX IF NOT EXISTS idx_dining_chair_products_category ON dining_chair_products(category);

ALTER TABLE dining_chair_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read dining_chair_products" ON dining_chair_products;
CREATE POLICY "Allow public read dining_chair_products"
  ON dining_chair_products
  FOR SELECT
  USING (true);

INSERT INTO dining_chair_products (
  category, name, brand, colour, warranty_in_months, country_of_origin,
  length, width, height, net_weight, description,
  generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name,
  price, images_url, product_url
) VALUES
($d$Collection / Dining Chairs$d$, $d$Casey Swivel Dining Chair In Olive And Tan Colour Set Of 2$d$, $d$ByUrban Ladder$d$, $d$Set Of 2$d$, 24, NULL, $d$59$d$, $d$62$d$, $d$86$d$, $d$18.00 kg$d$, $d$Buy Casey Swivel Dining Chair in Dual Tone & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$, NULL, $d$Engineered Wood$d$, NULL, NULL, NULL, NULL, 19999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/muOjw516I-Casey-Swivel-Dining-Chair-In-Olive-And-Tan-Colour-Set-Of-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/8aeclC-Kf2-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/WzHDgWiQKE-aa.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/VEBOSY9Q5t-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JkHB9B2MA-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/C8W-VBOL-C-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/jnV4A9EUx3-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LqH0yIWQtd-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/muOjw516I-Casey-Swivel-Dining-Chair-In-Olive-And-Tan-Colour-Set-Of-2.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/LhQDUuof3L-02.png$d$, $d$https://www.urbanladder.com/product/casey-swivel-dining-chair-in-dual-tone-8115847$d$),
($d$Collection / Dining Chairs$d$, $d$Bren Swivel Dining Chair In Auburn Fabric$d$, $d$ByUrban Ladder$d$, $d$options: Beige and Rust</li>$d$, 24, NULL, $d$56$d$, $d$64$d$, $d$88$d$, $d$19.00 kg$d$, $d$Buy Bren Swivel Dining Chair in Auburn Fabric & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 21999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/KnrpFI83t-a.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/TbUI5b86f-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/lnLLNcITHe-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ukXr7sL7jF-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/kkcQNoWQq8-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/47p2asbFp3-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/KnrpFI83t-a.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/TbUI5b86f-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/XBMR_j4PE-Bren-Swivel-Dining-Chair-In-Ivory-Colour.jpeg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/KnrpFI83t-a.png$d$, $d$https://www.urbanladder.com/product/bren-swivel-dining-chair-in-auburn-fabric-8115862$d$),
($d$Collection / Dining Chairs$d$, $d$Diner Solid Wood Dining Chair Set Of 2 In Dark Walnut Finish With Grey Colour Fabric - Urban Ladder$d$, $d$ByUrban Ladder$d$, $d$Fabric$d$, 12, NULL, $d$53$d$, $d$43$d$, $d$85$d$, $d$12.50 kg$d$, $d$Buy Diner Solid Wood Dining Chair set of 2 in Dark Walnut Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 9999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/Cg3jXWSL30c-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/-3rxXrluEJL-02.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/mlrHy5iR8GL-03.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ouTxBW99g-04.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/8JoH2yMuZx-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/plpf8cAbmA-06.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/B-0bzpEnAe-07.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/2ME_bp0QA8-08.jpg$d$, $d$https://www.urbanladder.com/product/diner-solid-wood-dining-chair-set-of-2-in-dark-walnut-finish-7519040$d$),
($d$Collection / Dining Chairs$d$, $d$Atlas Solid Wood Dining Chairs Set Of 2 in Honey Finish with Baltic Blue Colour$d$, $d$ByUrban Ladder$d$, $d$Chair Finish : Honey Qty : 1$d$, 36, NULL, $d$49$d$, $d$45$d$, $d$89$d$, $d$21.35 kg$d$, $d$Gather, linger, and savour every moment—because the Atlas Dining Chairs are designed for more than just meals. With their plush upholstered seating, they invite you to sit back and stay awhile, while their clean lines and contemporary design add effortless elegance to any space. Crafted from solid Mango wood and finished in a rich, warm tone, Atlas blends seamlessly into a variety of settings, from modern dining rooms to cozy breakfast nooks. A perfect balance of comfort and style, Atlas makes every moment feel special. - Available in Honey and Danish Walnut finish options. - Made from solid Mango wood. - Pair with Atlas Dining Table for a seamless look.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 9999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/RkA-tfc7oIg-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ra9XT-7HepV-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/O2E8uklJVxj-3.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/wz-2Wu6QCR6-4.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/JFStoe_iq-Atlas-Dining-Chairs-Set-of-2-Finish-Danish-walnut-Colour-Avocado-Green.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/RkA-tfc7oIg-1.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/zwBt3bFtxzm-02.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/ra9XT-7HepV-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/MO1V9HhUD_-2.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/DW7ET3AoVJ-2.jpg$d$, $d$https://www.urbanladder.com/product/atlas-dining-chairs-set-of-2-finish-honey-colour-baltic-blue-8716745$d$),
($d$Collection / Dining Chairs$d$, $d$Beck Swivel Metal Dining Chair Set Of 2 In Wine Fabric$d$, $d$ByUrban Ladder$d$, $d$Olive Leatherette Taupe Leatherette Wine$d$, 12, NULL, $d$66$d$, $d$61$d$, $d$91$d$, $d$19.50 kg$d$, $d$Settle into effortless style with the Beck dining chair. Its lounge-inspired silhouette embraces you with contoured creases on the backrest and seat, offering a tailored yet relaxed appeal. The high back and gently angled arms provide ergonomic support, inviting longer meals or quiet moments of reflection. A sleek swivel base lends a modern edge, letting you turn or rise with effortless ease. Perfect for chic dining spaces or home offices, Beck turns every moment into a lasting impression. - High-back design for effortless comfort. - Premium 330GSM fabric in Wine fabric and premium leatherette in Taupe and Olive leatherette. - Sleek metal legs in black finish.$d$, NULL, $d$Metal$d$, NULL, NULL, NULL, NULL, 24999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/5fP-oCz4n--LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/nq_68k2gC-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/v9yj9gHkN_-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/yIfmocLYyT-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/-2w19hQAN-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/DuZSF7wPRh-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/5fP-oCz4n--LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/q-AdoyL4--b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/TDFwpuU-7w-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/nq_68k2gC-b.jpg$d$, $d$https://www.urbanladder.com/product/beck-swivel-metal-dining-chair-set-of-2-in-wine-fabric-9253671$d$),
($d$Collection / Dining Chairs$d$, $d$Wella Swivel Solid Wood Dining Chair Set of 2 in Beige Fabric$d$, $d$ByUrban Ladder$d$, $d$options: Beige$d$, 12, NULL, $d$65$d$, $d$61$d$, $d$90$d$, $d$20.00 kg$d$, $d$The Wella chair’s bucket seat design embraces the body in a gentle curve, offering supportive armrests and a naturally reclined posture for leisurely dining. Upholstered in textured fabric with refined stitched detailing, it brings both visual and tactile richness to the table. Angled wooden legs in a walnut finish ground the silhouette with warmth, completing a look that’s timeless yet contemporary. - Bucket seat design with armrest. - 360-degree swivel function. - Premium textured fabric. - Available in three colour options: Beige, Blue & Terracotta.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 21999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ttHRMBYF6F-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Xa5xd93ih5-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/d_rBfY2L5-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/n8FMLpjv4D-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/rl2n3pPVz-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/qa9YMr9_M2-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/ttHRMBYF6F-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Xa5xd93ih5-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/QG-yR5kIF-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/MYEQLYRwek-b.jpg$d$, $d$https://www.urbanladder.com/product/wella-swivel-solid-wood-dining-chair-set-of-2-in-beige-fabric-9264233$d$),
($d$Collection / Dining Chairs$d$, $d$Tulip Swivel Dining Chair In Tan Colour$d$, $d$ByUrban Ladder$d$, $d$Qty : 1$d$, 24, NULL, $d$52$d$, $d$65$d$, $d$88$d$, $d$10.60 kg$d$, $d$Buy Tulip Swivel Dining Chair- Dual Tone & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$, NULL, $d$Metal$d$, NULL, NULL, NULL, NULL, 9999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/1ik79Yr1bzW-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/xmETeOmhlqU-02.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/cFF5QNYqOVy-03.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/jQXWq41-qOu-04.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YrXdPpZYEON-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YY_TYoLpeRy-06.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Fcv-jlcaf9T-07.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/In-e0nskfTU-08.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/1ik79Yr1bzW-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/oaB-tr_O5T-02.png$d$, $d$https://www.urbanladder.com/product/tulip-swivel-dining-chair-dual-tone-8115869$d$),
($d$Collection / Dining Chairs$d$, $d$Dalla Solid Wood Dining Chair Set Of 2 In Grey Colour$d$, $d$ByUrban Ladder$d$, $d$Qty : 1$d$, 12, NULL, $d$46$d$, $d$55$d$, $d$88$d$, $d$12.70 kg$d$, $d$Buy Dalla Solid Wood Dining Chair set of 2 in Finish & Get upto 70% off by Urban Ladder with 0% EMI, Free Delivery, Free Installation, shop at over 50+ Stores Nationwide.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 13999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LuzESXvUq-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/jxpz-dxENo-02.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/LQEo3VtBf2-03.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/vn-ePlBm4M-04.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/qM8c-8RFAL-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/p2jpNAJa9O-06.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/UNk_3mbxRF-07.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9osDVvyenc-08.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/LuzESXvUq-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/W3pv1k9X_W-02.png$d$, $d$https://www.urbanladder.com/product/dalla-solid-wood-dining-chair-set-of-2-in-finish-7519073$d$),
($d$Collection / Dining Chairs$d$, $d$Calix Swivel Metal Dining Chair Set of 2 in Beige Fabric$d$, $d$ByUrban Ladder$d$, $d$options$d$, 12, NULL, $d$62$d$, $d$63$d$, $d$82$d$, $d$21.00 kg$d$, $d$Graceful curves meet modern refinement in the Calix dining chair. Upholstered in a powder-textured fabric, it pairs softness with structure, elevated by elegant contrast piping that outlines its sculpted form. The gently contoured backrest and cushioned seat offer ergonomic comfort, while the sleek metal legs lend a touch of glamour. With a 180° swivel and auto-return feature, Calix adapts effortlessly to your rhythm of dining and conversation. Perfect around a premium dining table or as an accent in a lounge, it’s a chair that feels as good as it looks — poised, contemporary, and luxurious. - Features an 180-degree swivel with an auto return function. - Mid-contoured back. - Available in Beige and Powder Blue colour options.$d$, NULL, $d$Metal$d$, NULL, NULL, NULL, NULL, 21999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/YDbrqTufNH-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ikriBhd2S-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MxYa8cUW9-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/xZPt9iuL3c-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/PW-lIXbGnX-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/tWtkb_xoxt-h.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/YDbrqTufNH-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/ikriBhd2S-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Rnhifb6cZ9-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/200x0/YDbrqTufNH-LP.jpg$d$, $d$https://www.urbanladder.com/product/calix-swivel-metal-dining-chair-set-of-2-in-beige-fabric-9264229$d$),
($d$Collection / Dining Chairs$d$, $d$Oribi Solid Wood Dining Chair Set Of 2 In Teak Finish$d$, $d$ByUrban Ladder$d$, $d$Avocado Green Wheat Brown Out of Stock Burnt Orange$d$, 36, NULL, $d$48$d$, $d$44$d$, $d$88$d$, $d$21.35 kg$d$, $d$The Oribi Dining Chair redefines modern dining with its perfect balance of simplicity, strength, and comfort.  Built with a sturdy medium-back, it offers both support and effortless style, making every meal feel special. Expertly crafted from premium Sheesham wood, it showcases the beauty of solid wood while ensuring lasting durability. The cushioned upholstered seat provides superior comfort, making every meal a relaxed affair. Designed with clean lines and a minimalist aesthetic, the Oribi Dining Chair effortlessly complements any dining setup, from classic to modern. - The upholstered seat is generously cushioned for comfortable dining. - Made of high-grade Sheesham wood. - No assembly required. - Indoor use only.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 9999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/js-y0_j00D-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Om27UEJGk7-02.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/c6boQ_tEeH-03.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ujyYZqBq_G-04.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/kor5SwnDo6v-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ohIwkwpOAEV-06.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/MCiPxYD_KVf-07.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/js-y0_j00D-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/V_BijlC9cS-02.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/Om27UEJGk7-02.png$d$, $d$https://www.urbanladder.com/product/oribi-solid-wood-dining-chair-set-of-in-teak-finish-7519385$d$),
($d$Collection / Dining Chairs$d$, $d$Martha Solid Wood Dining Chair Set Of 2 In Teak Finish$d$, $d$ByUrban Ladder$d$, $d$Burnt Orange Wheat Brown$d$, 36, NULL, $d$51$d$, $d$45$d$, $d$1$d$, $d$19.00 kg$d$, $d$Experience timeless elegance and exceptional comfort with the Martha Dining Chair—a sophisticated addition to any dining space. Crafted from solid Sheesham wood, this chair is a testament to durability and craftsmanship. Designed for both aesthetics and function, the wooden backrest enhances air circulation, promoting comfort even during long meals. Complementing this is a plush, upholstered seat, generously padded and wrapped in premium fabric for a soft yet supportive feel. Whether hosting a formal dinner or enjoying everyday gatherings, the Martha Dining Chair offers the perfect balance of style, comfort, and lasting quality. - Made from solid Sheesham wood. - Upholstered, plush seat. - Please refer to images for dimension details. - Indoor use only.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 9999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/677uQTeggT-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ojerzvFQsm-02.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/Mk20tddKX7-03.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/OUTNvA0e-R-04.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/XLzFxpS3h0-05.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/ivzivYIbL_-06.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/fGwMQU7UDt-07.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/XEeXSUpVM3-08.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/677uQTeggT-01.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/mL95HhKPRUw-02.png$d$, $d$https://www.urbanladder.com/product/martha-solid-wood-dining-chair-set-of-2-in-teak-finish-7519057$d$),
($d$Collection / Dining Chairs$d$, $d$Dane Solid Wood Dining Chair Set of 2 in Honey Finish$d$, $d$ByUrban Ladder$d$, $d$Crush Sale â Up to 70% OFF! Shop Now$d$, 12, NULL, $d$51$d$, $d$49$d$, $d$85$d$, $d$11.50 kg$d$, $d$The Dane dining chair celebrates the elegance of solid wood through a form that feels fluid and enduring. Defined by its softly rounded edges and slender proportions, the design lends a sense of lightness and poise to any dining space. The three gracefully curved slats on the backrest add a sense of rhythm while offering ergonomic support that encourages relaxed seating. Its contoured seat appears to float lightly within the frame, creating visual balance and showcasing the natural beauty of the wood. Perfect for both casual and formal dining settings, the Dane chair blends modern craftsmanship with timeless appeal, making it a versatile choice for interiors that value comfort as much as design clarity. - Made from solid Mango wood. - Available in 2 finish options: Danish Walnut and Honey.$d$, NULL, $d$Solid Wood$d$, NULL, NULL, NULL, NULL, 12999.0, $d$https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/THVo5ipUM-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/dykYiSWZkc-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/R5X9AyU-j-a.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/_V7_PpGiqG-c.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/rPLSRTSxqS-d.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/9zYfPu-jtv-e.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/100x0/bZg6S0gG6g-f.png | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/original/THVo5ipUM-LP.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/VaM8lz38U-b.jpg | https://cdn.swadeshonline.com/v2/patient-paper-41f385/swad-p/wrkr/products/pictures/item/free/150x0/dykYiSWZkc-b.jpg$d$, $d$https://www.urbanladder.com/product/dane-solid-wood-dining-chair-set-of-2-in-honey-finish-9264243$d$);

CREATE TABLE IF NOT EXISTS dinning_products (
  id bigserial PRIMARY KEY,
  category text,
  name text NOT NULL,
  brand text,
  colour text,
  warranty_in_months int,
  country_of_origin text,
  length text,
  width text,
  height text,
  net_weight text,
  description text,
  generic_name text,
  primary_material_type text,
  primary_material_subtype text,
  primary_room text,
  seating_capacity text,
  product_model_name text,
  price numeric(12,2),
  images_url text,
  product_url text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dinning_products_brand ON dinning_products(brand);
CREATE INDEX IF NOT EXISTS idx_dinning_products_category ON dinning_products(category);
CREATE INDEX IF NOT EXISTS idx_dinning_products_product_url ON dinning_products(product_url);

ALTER TABLE dinning_products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read dinning_products" ON dinning_products;
CREATE POLICY "Allow public read dinning_products"
  ON dinning_products
  FOR SELECT
  USING (true);

INSERT INTO dinning_products (
  category, name, brand, colour, warranty_in_months, country_of_origin,
  length, width, height, net_weight, description,
  generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name,
  price, images_url, product_url
)
SELECT
  category, name, brand, colour, warranty_in_months, country_of_origin,
  length, width, height, net_weight, description,
  generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name,
  price, images_url, product_url
FROM dining_table_products;

INSERT INTO dinning_products (
  category, name, brand, colour, warranty_in_months, country_of_origin,
  length, width, height, net_weight, description,
  generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name,
  price, images_url, product_url
)
SELECT
  category, name, brand, colour, warranty_in_months, country_of_origin,
  length, width, height, net_weight, description,
  generic_name, primary_material_type, primary_material_subtype, primary_room, seating_capacity, product_model_name,
  price, images_url, product_url
FROM dining_chair_products;

DROP TABLE IF EXISTS dining_table_products;
DROP TABLE IF EXISTS dining_chair_products;
